### ISSUE TITLE
I designed an economy today LOL

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/TEC-Hatch-Vote#12]
<h1>Parameters</h1>

| Parameters                          |   Values |
|:------------------------------------|---------:|
| Target raise (wxDai)                | 10000000 |
| Maximum raise (wxDai)               | 25000000 |
| Minimum raise (wxDai)               |  1250000 |
| Impact hour slope (wxDai/IH)        |      351 |
| Maximum impact hour rate (wxDai/IH) |      300 |
| Hatch oracle ratio (wxDai/CSTK)     |       50 |
| Hatch period (days)                 |       21 |
| Hatch exchange rate (TECH/wxDai)    |     1000 |
| Hatch tribute (%)                   |       23 |
| Support required (%)                |       65 |
| Minimum accepted quorum (%)         |        8 |
| Vote duration (days)                |        3 |
| Vote buffer (hours)                 |        3 |
| Rage quit (hours)                   |       12 |
| Tollgate fee (wxDai)                |      500 |
            
<h1>Results</h1>

<p></p>

- It costs 500 wxDai to make a proposal.

- Votes will be voted on for 3 days.

- TECH token holders will have 12 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There will be a minimum of 3 hours between proposals so people can exit safely in weird edge case scenarios.

- A proposal that passes can be executed 15 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 100000 wxDai to the Hatch.

![nideadog](https://user-images.githubusercontent.com/75956027/115770842-0de27700-a362-11eb-8041-a35246b580c2.jpg)

Play with my parameters <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351&maxihr=300&ihtr=10000000&ihmaxr=25000000&hor=50&hpd=21&her=1000&ht=23&sr=65&maq=8&vdd=3&vbh=3&rqh=12&tfx=500" target="_blank">here</a>.

To see the value of your individual Impact Hours, click <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351&maxihr=300&ihtr=10000000&ihmaxr=25000000&hor=50&hpd=21&her=1000&ht=23&sr=65&maq=8&vdd=3&vbh=3&rqh=12&tfx=500" target="_blank">here to go to the Hatch Config Dashboard with these parameters</a> and explore the Impact Hour Results table.
            

<h1>Output Charts</h1>

![image](https://hcti.io/v1/image/43406b79-b5cd-40a2-b288-da22b2091ad2)

<h1>Output Scenarios</h1>

![image](https://hcti.io/v1/image/a4bc7a4b-65ec-4d09-8228-6d70480edaab)

**Comment by chuygarcia92** [comment]
OK, so I started tweaking my params based on some stuff I'm learning in the params party. Any suggestions are welcome and help a lot to better understand the dashboard :)


<h1>Parameters</h1>

| Parameters                          |           Values |
|:------------------------------------|-----------------:|
| Target raise (wxDai)                | 10,000,000.00    |
| Maximum raise (wxDai)               | 25,000,000.00    |
| Minimum raise (wxDai)               |  1,250,000.00    |
| Impact hour slope (wxDai/IH)        |           351.00 |
| Maximum impact hour rate (wxDai/IH) |           300.00 |
| Hatch oracle ratio (wxDai/CSTK)     |            50.00 |
| Hatch period (days)                 |            14.00 |
| Hatch exchange rate (TECH/wxDai)    |      1,000.00    |
| Hatch tribute (%)                   |            18.00 |
| Support required (%)                |            62.00 |
| Minimum accepted quorum (%)         |             8.00 |
| Vote duration (days)                |             3.00 |
| Vote buffer (hours)                 |             3.00 |
| Rage quit (hours)                   |            12.00 |
| Tollgate fee (wxDai)                |           500.00 |
            
<h1>Results</h1>

<p></p>

- It costs 500.0 wxDai to make a proposal.

- Votes will be voted on for 3 days.

- TECH token holders will have 12 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There will be a minimum of 3 hours between proposals so people can exit safely in weird edge case scenarios.

- A proposal that passes can be executed 15 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 100000 wxDai to the Hatch.

Play with my parameters <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351.0&maxihr=300.0&ihtr=10000000&ihmaxr=25000000&hor=50.0&hpd=14&her=1000.0&ht=18&sr=62&maq=8&vdd=3&vbh=3&rqh=12&tfx=500.0" target="_blank">here</a>.

To see the value of your individual Impact Hours, click <a href="https://params.tecommons.org/hatch?ihminr=1250000&hs=351.0&maxihr=300.0&ihtr=10000000&ihmaxr=25000000&hor=50.0&hpd=14&her=1000.0&ht=18&sr=62&maq=8&vdd=3&vbh=3&rqh=12&tfx=500.0" target="_blank">here to go to the Hatch Config Dashboard with these parameters</a> and explore the Impact Hour Results table.
            

<h1>Output Charts</h1>

![image](https://hcti.io/v1/image/a57c1f28-dce2-4194-83b2-1910d0bfcc3f)

<h1>Output Scenarios</h1>

![image](https://hcti.io/v1/image/2a1c11c1-c1fc-425b-952d-278bdb266f0f)

**Comment by GriffGreen** [comment]
Wow! This is optimistic! you think we are going to get 10 mill! We might, and if so this is a proposal that really favors the Builders over the Backers.... 

Because the Builders are sooooo heavily rewarded, I am skeptical that we will get 10 mil as a target goal

**Comment by chuygarcia92** [comment]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=1250000&tgihr=110&maxihr=120&ihtr=12000000&ihmaxr=15000000&hor=100&hpd=21&her=50&ht=18&sr=65&maq=7&vdd=3&vbh=3&rqh=12&tfx=3000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/d35c2eaa-a37e-45ce-9337-ec5cbabce73c)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/7e7d4e00-48ba-4180-a344-68e1072b3459)
            
## Hatch Strategy

<p>I made some adjustments with more awareness about the relation between backers and conviction voting in the DAO, I also adjusted @GriffGreen 's tip on not favoring builders so much so the 10M target has more chances to be reached.</p>
            
## DAO Strategy

<p>To use the defaults... Technocracy for the win</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 12000000 wxDai, with a minimum of 1250000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 15000000 wxDai.

- Backers will need to send in 0.02 wxDai to mint 1 TECH.

- The membership ratio is set at 100 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 112500  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 65% support, and a minimum of 7% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 12 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 3 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 2920 votes per year.

- To prevent griefing attacks, it will cost 3000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=1250000&tgihr=110&maxihr=120&ihtr=12000000&ihmaxr=15000000&hor=100&hpd=21&her=50&ht=18&sr=65&maq=7&vdd=3&vbh=3&rqh=12&tfx=3000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|12,000,000|
|Maximum Goal (wxDai)|15,000,000|
|Minimum Goal (wxDai)|1,250,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|110|
|Impact Hour Rate at Infinity (wxDai/IH)|120|
|Hatch Membership Ratio (wxDai/CSTK)|100|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|50|
|Hatch Tribute (%)|18|
|Support Required (%)|65|
|Minimum Quorum (%)|7|
|Vote Duration (days)|3|
|Vote Buffer (hours)|3|
|Ragequit (hours)|12|
|Tollgate Fee (wxDai)|12|</a>

**Comment by chuygarcia92** [comment]
I started from scratch in issue #27 so I'll close this issue since it was more experimental
