### ISSUE TITLE
Display the dashboard link in the Tokenlog issue 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/TEC-Hatch-Vote#13]
Once Tokenlog is working to display the content of the issue in the initial page, we can have the dashboard link displayed in the front of the issue instead of having to open it on github. 

Would be nice to think of a nice visual experience of the results to open many tabs and compare them. 
Would be possible to have a section in the dashboard page to compare different params submissions?

**Comment by GriffGreen** [comment]
@liviade1 this is not the place for issues... 

This is: https://github.com/CommonsBuild/Token-Log-Hatch-Params/issues/

Transferred your issue over tho, made it part of the output Github issue UX overhaul, Mitch and Lauren are on it!

https://github.com/CommonsBuild/Token-Log-Hatch-Params/issues/241
