### ISSUE TITLE
have it explained that the backers are paying a tribute to the builders by dilution of TECH tokens

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/TEC-Hatch-Vote#14]
suggestion to change the question mark of the "maximum impact hour rate" from 'The theoretical maximum rate that Impact Hour token holders would be able to receive.' to - The maximum rate that IH token holders would receive from TECH token dilution provided by the backers 
I don't know if what I wrote is right 😅 but something to explain this relationship

**Comment by GriffGreen** [comment]
@liviade1 this is not the place for issues... 

This is: https://github.com/CommonsBuild/Token-Log-Hatch-Params/issues/

Transferred your issue over tho

https://github.com/CommonsBuild/Token-Log-Hatch-Params/issues/249
