### ISSUE TITLE
Close to the Default Params! 🙌 (From hacking party)

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/TEC-Hatch-Vote#19]
<h1>Parameters</h1>

| Parameters                                 |   Values |
|:-------------------------------------------|---------:|
| Target raise (wxDai)                       |  5000000 |
| Maximum raise (wxDai)                      | 15000000 |
| Minimum raise (wxDai)                      |   300000 |
| Impact Hour Rate at Target Goal (wxDai/IH) |      150 |
| Maximum impact hour rate (wxDai/IH)        |      500 |
| Hatch oracle ratio (wxDai/CSTK)            |       10 |
| Hatch period (days)                        |       15 |
| Hatch exchange rate (TECH/wxDai)           |      100 |
| Hatch tribute (%)                          |        5 |
| Support required (%)                       |       70 |
| Minimum accepted quorum (%)                |        2 |
| Vote duration (days)                       |        3 |
| Vote buffer (hours)                        |       24 |
| Rage quit (hours)                          |       12 |
| Tollgate fee (wxDai)                       |     1000 |
            

<h2>Hatch Comments</h2>

<p>Its great for Zepti to raise a 100 K! and the distribution in the list looks good with most default parameters.
Impact Hour Rate at Target Goal: 150 (wxDai/IH)
Maximum Goal (wxDai): 15 million
Minimum Goal (wxDai): 300 k
Hatch Minting Rate (TECH/wxDai): 100</p>
            

<h2>Dandelion Voting Comments</h2>

<p>Think is good to have 12 hours for people to exit the DAO if they don't like the results of a vote, and 24 hours between proposals so people have time to exit safely if they voted yes on a previous vote. At most 265 votes per year.</p>
            <h1>Summary</h1>

 <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 15 days.

- The target goal will be 5000000 wxDai, with a minimum of 300000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 15000000 wxDai.

- Backers will need to send in 0.01 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 12250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 70% support, and a minimum of 2% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 12 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 24 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 365 votes per year.

- To prevent griefing attacks, it will cost 1000 wxDai to make a proposal.

Play with my parameters <a href="https://params.tecommons.org/hatch?ihminr=300000&tgihr=150&maxihr=500&ihtr=5000000&ihmaxr=15000000&hor=10&hpd=15&her=100&ht=5&sr=70&maq=2&vdd=3&vbh=24&rqh=12&tfx=1000" target="_blank">here</a>.

To see the value of your individual Impact Hours, click <a href="https://params.tecommons.org/hatch?ihminr=300000&tgihr=150&maxihr=500&ihtr=5000000&ihmaxr=15000000&hor=10&hpd=15&her=100&ht=5&sr=70&maq=2&vdd=3&vbh=24&rqh=12&tfx=1000" target="_blank">here to go to the Hatch Config Dashboard with these parameters</a> and explore the Impact Hour Results table.
            

<h1>Output Charts</h1>

![image](https://hcti.io/v1/image/1b12f177-7c29-4750-a1cb-40d3b21b8c29)

<h1>Output Scenarios</h1>

![image](https://hcti.io/v1/image/b85daf8b-1f72-4fa6-bfe6-38bda8d28729)

**Comment by GriffGreen** [comment]
@JuankBell  I am closing this cause it is using the template... and the Impact hour Rate Graph has different axis range than other proposals.
If you want to resubmit, click the link up there as you would to fork it... and it will pop back up, with the right formatting
