### ISSUE TITLE
Choosing Params like Goldilocks - not too hot, not too cold

### ISSUE THREAD

**Issue by laurenluz** [CommonsBuild/TEC-Hatch-Vote#26]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=50&maxihr=150&ihtr=2000000&ihmaxr=8000000&hor=5.0&hpd=15&her=0.01&ht=10&sr=80&maq=5&vdd=3&vbh=24&rqh=24&tfx=5000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://user-images.githubusercontent.com/75490971/117036119-57b45100-acc2-11eb-9f08-9fabd605f3a3.png)

# Graphical Summary

![image](https://hcti.io/v1/image/fd90843f-ee89-406e-894e-606cbf47ab76)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/e0efb6a8-5245-48e9-afbf-bcb62537f9ae)
            
## Hatch Strategy

<p>This is fork of https://github.com/CommonsBuild/TEC-Hatch-Vote/issues/17

I did like the bias towards the Builders but wanted to choose params that seemed a little more balanced. Also, I think we can do better in raising funds with the community we currently have, so I raised the caps. Nothing too crazy, but hey, 8 is a pretty nice number energetically.

So I left these variables the same
Hatch Tribute
Membership ratio
Hatch Period
Hatch Minting rate

I changed:
Min goal
Max goal
Target goal
Impact Hour rate
Impact Hour rate at infinity

I made all the goals a little higher and set the impact hour rate at target to a nice, round number of 50wxDai at target.

To be honest, I chose these params with just little bit of logic and a lot of "because it felt better that way".</p>
            
## DAO Strategy

<p>Also a fork of https://github.com/CommonsBuild/TEC-Hatch-Vote/issues/17

I adjusted the vote proposal buffer because our community is super international so theoretically we could be the dangerous edge case of someone voting yes on a proposal then going into a long deep sleep, having a malicious proposal jump in an get support, and then our sleeping friend loses the opportunity to rage quit. So I changed it from 8 to 24 hours. I also upped the tollgate fee to 5000 wxdai because it seems logical that a longer vote proposal buffer begets a larger tollgate fee: should cost more to "delay" the community for more time.

I didn't change:
support required
minimum quorum
vote duration
rage quit delay

They all felt "just right" </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 15 days.

- The target goal will be 2000000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8000000 wxDai.

- Backers will need to send in 100.0 wxDai to mint 1 TECH.

- The membership ratio is set at 5.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 5625  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 80% support, and a minimum of 5% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 24 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 365 votes per year.

- To prevent griefing attacks, it will cost 5000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=50&maxihr=150&ihtr=2000000&ihmaxr=8000000&hor=5.0&hpd=15&her=0.01&ht=10&sr=80&maq=5&vdd=3&vbh=24&rqh=24&tfx=5000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2,000,000|
|Maximum Goal (wxDai)|8,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|50|
|Impact Hour Rate at Infinity (wxDai/IH)|150|
|Hatch Membership Ratio (wxDai/CSTK)|5.0|
|Hatch Period (days)|15|
|Hatch Minting rate (TECH/wxDai)|0.01|
|Hatch Tribute (%)|10|
|Support Required (%)|80|
|Minimum Quorum (%)|5|
|Vote Duration (days)|3|
|Vote Buffer (hours)|24|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|5000|</a>

**Comment by JuankBell** [comment]
Great params! would only raise the Tollgate fee // **Update**: great that now it displays your choice!

**Comment by laurenluz** [comment]
That looks like an error! I set it to 5000wxDai... if you open my params you can see it right there in the dashboard. @marthendalnunes can you look into this?

I set the tollgate fee to 5000wxDai, and in the "config" table it has it showing up as 24wxDai

**Comment by marthendalnunes** [comment]
@laurenluz thanks for the feedback, found the error and going to commit the changes to fix it. You can either rerun it and post the issue again or just edit this issue markdown with the correct value.

**Comment by laurenluz** [comment]
Awesome! I just edited the issue - Thanks Vitor! you rock 🚀

**Comment by GriffGreen** [comment]
I love the elegance of this proposal. 25 wxdai/ih at the min,  50 wxdai/ih at the target, 100 wxdai/ih at the max... honestly its just really easy to explain to people! I will make a fork for sure.

One thing I want to correct...

> I adjusted the vote proposal buffer because our community is super international so theoretically we could be the dangerous edge case of someone voting yes on a proposal then going into a long deep sleep, having a malicious proposal jump in an get support, and then our sleeping friend loses the opportunity to rage quit. 

The vote proposal buffer is a rate limiter for proposals... as in, it slows the number of newly created milestones. if that is set to 10 days, it means we can create 1 proposal every 10 days... 

For example... If: 
- Vote Proposal Buffer is 10 days
- Vote Duration is 1 day 
- Ragequit Delay is 1 hour 

Then if 1 vote is proposed, the next vote cannot be PROPOSED for 10 days 

BUT!

That vote can pass within 24 hours and be executed 1 hour later.  

The 2 params that address the issue you are thinking about are:
- Vote Duration  
- Ragequit Delay 

Ragequit Delay being the primary one

**Comment by marthendalnunes** [comment]
Testing tokenlog (please ignore it)

**Comment by GriffGreen** [comment]
Thank you for submitting @laurenluz! This was a very influential proposal. Getting 6th place and 311 votes and setting the stage early for the idea of setting params to get simple round numbers for outputs.  We are closing all the submissions for the next round of voting.
