### ISSUE TITLE
I made an economy that made me giggle at first but I have learned to take more seriously as I fall deeper into the Dashboard rabbit hole (Fork of #12)

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/TEC-Hatch-Vote#27]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=1250000&tgihr=110&maxihr=120&ihtr=12000000&ihmaxr=15000000&hor=100&hpd=21&her=50&ht=18&sr=65&maq=7&vdd=3&vbh=3&rqh=12&tfx=3000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://cdn.discordapp.com/attachments/810180622165213222/837792747711627264/Sidelined_and_Scared.png)

# Graphical Summary

![image](https://hcti.io/v1/image/d35c2eaa-a37e-45ce-9337-ec5cbabce73c)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/7e7d4e00-48ba-4180-a344-68e1072b3459)
            
## Hatch Strategy

<p>This is a fork of #12, I made some adjustments with more awareness about the relation between backers and the voting process in the DAO, I also applied @GriffGreen 's tip on not favoring builders so much so the 10M target has more chances to be reached.</p>
            
## DAO Strategy

<p>To use the defaults... Technocracy for the win</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 12000000 wxDai, with a minimum of 1250000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 15000000 wxDai.

- Backers will need to send in 0.02 wxDai to mint 1 TECH.

- The membership ratio is set at 100 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 112500  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 65% support, and a minimum of 7% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 12 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 3 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 2920 votes per year.

- To prevent griefing attacks, it will cost 3000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=1250000&tgihr=110&maxihr=120&ihtr=12000000&ihmaxr=15000000&hor=100&hpd=21&her=50&ht=18&sr=65&maq=7&vdd=3&vbh=3&rqh=12&tfx=3000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|12,000,000|
|Maximum Goal (wxDai)|15,000,000|
|Minimum Goal (wxDai)|1,250,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|110|
|Impact Hour Rate at Infinity (wxDai/IH)|120|
|Hatch Membership Ratio (wxDai/CSTK)|100|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|50|
|Hatch Tribute (%)|18|
|Support Required (%)|65|
|Minimum Quorum (%)|7|
|Vote Duration (days)|3|
|Vote Buffer (hours)|3|
|Ragequit (hours)|12|
|Tollgate Fee (wxDai)|12|</a>

**Comment by GriffGreen** [comment]
@chuygarcia92 why did you pick a high hatch tribute?
