### ISSUE TITLE
Testing Params for Vitor / Fabio

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/TEC-Hatch-Vote#3]
<h1>Parameters</h1>

| Parameters                          |   Values |
|:------------------------------------|---------:|
| Target raise (wxDai)                |  3000000 |
| Maximum raise (wxDai)               | 50000000 |
| Minimum raise (wxDai)               |   500000 |
| Impact hour slope (wxDai/IH)        |     1535 |
| Maximum impact hour rate (wxDai/IH) |      255 |
| Hatch oracle ratio (wxDai/CSTK)     |       15 |
| Hatch period (days)                 |       21 |
| Hatch exchange rate (TECH/wxDai)    |    15000 |
| Hatch tribute (%)                   |        5 |
| Support required (%)                |       80 |
| Minimum accepted quorum (%)         |        5 |
| Vote duration (days)                |       14 |
| Vote buffer (hours)                 |        4 |
| Rage quit (hours)                   |       24 |
| Tollgate fee (wxDai)                |     1000 |
            
<h1>Results</h1>

<p>Testing Params for Vitor and Fabio</p>

- It costs 1000 wxDai to make a proposal.

- Votes will be voted on for 14 days.

- TECH token holders will have 24 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There will be a minimum of 4 hours between proposals so people can exit safely in weird edge case scenarios.

- A proposal that passes can be executed 28 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 30000 wxDai to the Hatch.

Play with my parameters [here](https://params.tecommons.org/hatch?ihminr=500000&hs=1535&maxihr=255&ihtr=3000000&ihmaxr=50000000&hor=15&hpd=21&her=15000&ht=5&sr=80&maq=5&vdd=14&vbh=4&rqh=24&tfx=1000).

To see the value of your individual Impact Hours, click [here to go to the Hatch Config Dashboard with these parameters](https://params.tecommons.org/hatch?ihminr=500000&hs=1535&maxihr=255&ihtr=3000000&ihmaxr=50000000&hor=15&hpd=21&her=15000&ht=5&sr=80&maq=5&vdd=14&vbh=4&rqh=24&tfx=1000) and explore the Impact Hour Results table.
            

<h1>Output Charts</h1>

![image](https://hcti.io/v1/image/29d8db3c-34c4-43e1-824c-d0e81139ba7e)

<h1>Output Scenarios</h1>

![image](https://hcti.io/v1/image/931164d3-09ee-4abd-95f6-62265da3d2be)

**Comment by GriffGreen** [comment]
Closing this issue because the math is wrong in the outputs... please re-propose @freedumbs00
