### ISSUE TITLE
Builders - Incentivized Raise Strategy

### ISSUE THREAD

**Issue by natenatesoo** [CommonsBuild/TEC-Hatch-Vote#30]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=700000&tgihr=25&maxihr=248&ihtr=900000&ihmaxr=50000000&hor=20&hpd=42&her=100&ht=4&sr=90&maq=8&vdd=5&vbh=12&rqh=2&tfx=2500" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/0d86c148-d8ba-4835-b2de-2dd0c5dc9ead)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/e53dd228-dd93-4a55-87b3-761b9b321e00)
            
## Hatch Strategy

<p>Established a higher Minimum Goal (wxDAI), and a lower IH rate at Infinity to incentivize Builders to seek more funds for the Hatch Raise.

Increased the Hatch Period to a little over a month.  </p>
            
## DAO Strategy

<p>Increased Vote Duration Period, Increased Tollgate Fee, Increased Vote Proposal Buffer, and Increased time to Ragequit.

High Support, Moderate Quorum Required.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 42 days.

- The target goal will be 900000 wxDai, with a minimum of 700000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 50000000 wxDai.

- Backers will need to send in 0.01 wxDai to mint 1 TECH.

- The membership ratio is set at 20 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 22500  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 5 days. They will require at least 90% support, and a minimum of 8% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 2 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 12 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 730 votes per year.

- To prevent griefing attacks, it will cost 2500 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=700000&tgihr=25&maxihr=248&ihtr=900000&ihmaxr=50000000&hor=20&hpd=42&her=100&ht=4&sr=90&maq=8&vdd=5&vbh=12&rqh=2&tfx=2500" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|900,000|
|Maximum Goal (wxDai)|50,000,000|
|Minimum Goal (wxDai)|700,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|25|
|Impact Hour Rate at Infinity (wxDai/IH)|248|
|Hatch Membership Ratio (wxDai/CSTK)|20|
|Hatch Period (days)|42|
|Hatch Minting rate (TECH/wxDai)|100|
|Hatch Tribute (%)|4|
|Support Required (%)|90|
|Minimum Quorum (%)|8|
|Vote Duration (days)|5|
|Vote Buffer (hours)|12|
|Ragequit (hours)|2|
|Tollgate Fee (wxDai)|2,500|</a>

**Comment by GriffGreen** [comment]
Thank you for submitting @natenatesoo! We are closing all the submissions. This submission didn't get very many votes but it blazed a trail for a lot of people, intro'ing people to this effort, I used it several times in Param parties ;-D
