### ISSUE TITLE
TEC Hatch Params with a high max goal 

### ISSUE THREAD

**Issue by PJColombo** [CommonsBuild/TEC-Hatch-Vote#31]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=1500000&tgihr=55&maxihr=590&ihtr=4500000&ihmaxr=10000000&hor=10.0&hpd=21&her=8000.0&ht=15&sr=65&maq=3&vdd=5&vbh=12&rqh=2&tfx=750.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/f9669c5e-820d-4713-b9f8-733121641b36)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/690a19be-b2e3-492c-8e9d-c3c11b97458d)
            
## Hatch Strategy

<p>To use the defaults... Technocracy for the win</p>
            
## DAO Strategy

<p>To use the defaults... Technocracy for the win</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 4500000 wxDai, with a minimum of 1500000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 10000000 wxDai.

- Backers will need to send in 0.000125 wxDai to mint 1 TECH.

- The membership ratio is set at 10.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 5 days. They will require at least 65% support, and a minimum of 3% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 2 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 12 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 730 votes per year.

- To prevent griefing attacks, it will cost 750.0 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=1500000&tgihr=55&maxihr=590&ihtr=4500000&ihmaxr=10000000&hor=10.0&hpd=21&her=8000.0&ht=15&sr=65&maq=3&vdd=5&vbh=12&rqh=2&tfx=750.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|4,500,000|
|Maximum Goal (wxDai)|10,000,000|
|Minimum Goal (wxDai)|1,500,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|55|
|Impact Hour Rate at Infinity (wxDai/IH)|590|
|Hatch Membership Ratio (wxDai/CSTK)|10.0|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|8,000.0|
|Hatch Tribute (%)|15|
|Support Required (%)|65|
|Minimum Quorum (%)|3|
|Vote Duration (days)|5|
|Vote Buffer (hours)|12|
|Ragequit (hours)|2|
|Tollgate Fee (wxDai)|750.0|</a>

**Comment by GriffGreen** [comment]
Thank you for submitting @PJColombo! This was a very nice proposal, going for big money!!! 

It got 20 votes! We are closing all the submissions for the next round of voting.
