### ISSUE TITLE
Nuggan's raise-a-lot

### ISSUE THREAD

**Issue by PabloCGL** [CommonsBuild/TEC-Hatch-Vote#32]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=120&maxihr=300&ihtr=9000000&ihmaxr=15000000&hor=50&hpd=10&her=1&ht=7&sr=60&maq=10&vdd=3&vbh=8&rqh=36&tfx=1000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/68ecbc95-687b-4900-b276-aec2329dd5d7)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/7af6f071-3c25-4386-b036-f9bd5bc0387b)
            
## Hatch Strategy

<p>The goal of this params is to try to make a big hatch and raise a lot of money. For that I set the membership ratio at 50, so even people with a low CSTK score can send up to 50000$. 
To counterbalance this "dilution" by people with less skin in the game, I also set a fairly high hatch tribute to disincentivize jumping ship once the hatch is done. 
The 300 IH at Infinity may seem high, but in the table you can see that the actual rate at the maximum goal would be ~160, which is more palatable given the raised amount would be 15000000.  
The hatch should last 10 days to allow for people to have time to contribute but also not let the hype die down. 
Since the TECH token will be converted anyway after the hatch, I just kept the minting ratio at 1 wxDai.</p>
            
## DAO Strategy

<p>The paramaters for dandelion voting should take into account the potentially more fragmented holder base. Since the only purpose of the hatch is to launch the DAO, I think we can expect higher involvement, specially from the builders:
The minimum quorum is set at 10%, which should be easily reachable, specially with coordinated with builder involvement. 
A required 60% support rate to pass should grant legitimacy to the winning vote. 
Proposals should feel weighty, so the tollgate is set at 1000, with a maximum of 3 per day.
Once voted, the 36 hours ragequit should give everybody a full day to think about withdrawing irrespective of the timezone they were in when the vote happened.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 10 days.

- The target goal will be 9000000 wxDai, with a minimum of 500000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 15000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 50 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 56250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 60% support, and a minimum of 10% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 36 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 1000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=120&maxihr=300&ihtr=9000000&ihmaxr=15000000&hor=50&hpd=10&her=1&ht=7&sr=60&maq=10&vdd=3&vbh=8&rqh=36&tfx=1000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|9,000,000|
|Maximum Goal (wxDai)|15,000,000|
|Minimum Goal (wxDai)|500,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|120|
|Impact Hour Rate at Infinity (wxDai/IH)|300|
|Hatch Membership Ratio (wxDai/CSTK)|50|
|Hatch Period (days)|10|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|7|
|Support Required (%)|60|
|Minimum Quorum (%)|10|
|Vote Duration (days)|3|
|Vote Buffer (hours)|8|
|Ragequit (hours)|36|
|Tollgate Fee (wxDai)|1,000|</a>

**Comment by GriffGreen** [comment]
Nice Proposal @PabloCGL ! Why such a short Hatch Period tho... Our Comms team can keep the hype going!!! :-D Honestly I just want more time to build the next dashboard and test the Commons Upgrade ;-)
