### ISSUE TITLE
1 million dollar baby

### ISSUE THREAD

**Issue by sembrestels** [CommonsBuild/TEC-Hatch-Vote#33]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=1000000&tgihr=120&maxihr=200&ihtr=5000000&ihmaxr=15000000&hor=10.0&hpd=15&her=100.0&ht=5&sr=70&maq=2&vdd=3&vbh=24&rqh=24&tfx=1000.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.pinimg.com/600x315/2a/d6/3f/2ad63f0f2333d5bc0e423689f90ef38d.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/662d1650-b201-44f7-a010-792b97ac483d)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/aba90bf9-60fc-4f6a-8293-28fe0694fc3c)
            
## Hatch Strategy

<p>I feel like we can get 1M</p>
            
## DAO Strategy

<p>Let's give more time for rage quitting after the vote has passed</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 15 days.

- The target goal will be 5000000 wxDai, with a minimum of 1000000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 15000000 wxDai.

- Backers will need to send in 0.01 wxDai to mint 1 TECH.

- The membership ratio is set at 10.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 70% support, and a minimum of 2% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 24 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 365 votes per year.

- To prevent griefing attacks, it will cost 1000.0 wxDai to make a proposal. 

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=1000000&tgihr=120&maxihr=200&ihtr=5000000&ihmaxr=15000000&hor=10.0&hpd=15&her=100.0&ht=5&sr=70&maq=2&vdd=3&vbh=24&rqh=24&tfx=1000.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|5,000,000|
|Maximum Goal (wxDai)|15,000,000|
|Minimum Goal (wxDai)|1,000,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|120|
|Impact Hour Rate at Infinity (wxDai/IH)|200|
|Hatch Membership Ratio (wxDai/CSTK)|10.0|
|Hatch Period (days)|15|
|Hatch Minting rate (TECH/wxDai)|100.0|
|Hatch Tribute (%)|5|
|Support Required (%)|70|
|Minimum Quorum (%)|2|
|Vote Duration (days)|3|
|Vote Buffer (hours)|24|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|1,000.0|</a>

**Comment by GriffGreen** [comment]
Great proposal @sembrestels !! Thank you for representing the Technocracy with style and classic meme-age. This was very influential, inspiring the target goal for many proposals, including #76 which got third place. 

This got 110 votes.  We are closing all the submissions for the next round of voting.
