### ISSUE TITLE
Do or do not, there is no try

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/TEC-Hatch-Vote#37]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=100&maxihr=200&ihtr=3500000&ihmaxr=8000000&hor=10&hpd=30&her=1&ht=20&sr=80&maq=35&vdd=5&vbh=12&rqh=24&tfx=1000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/c1d8c6d3-b0ac-4aa9-a8d4-94f48a3298e4)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/7da90a08-3819-4a47-8f0d-5052c371454f)
            
## Hatch Strategy

<p>Higher Hatch tribute to attract mission and vision an aligned “investors”.</p>
            
## DAO Strategy

<p>Modest proposal buffer time, reasonable Tollgate to incentivize proposal creation but also prevent malicious behavior. 
24 hours for rage quit accommodating members in different time zones. 

Quorum is set higher becuause this is is a closed membership DAO and will most likely reach the quorum because we're making important and one time decisions at this stage of the DAO. Enough time has been given for a members to vote, within a work week anyone can find time to vote on a single proposal.  </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 30 days.

- The target goal will be 3500000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 5 days. They will require at least 80% support, and a minimum of 35% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 12 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 730 votes per year.

- To prevent griefing attacks, it will cost 1000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=100&maxihr=200&ihtr=3500000&ihmaxr=8000000&hor=10&hpd=30&her=1&ht=20&sr=80&maq=35&vdd=5&vbh=12&rqh=24&tfx=1000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,500,000|
|Maximum Goal (wxDai)|8,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|100|
|Impact Hour Rate at Infinity (wxDai/IH)|200|
|Hatch Membership Ratio (wxDai/CSTK)|10|
|Hatch Period (days)|30|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|20|
|Support Required (%)|80|
|Minimum Quorum (%)|35|
|Vote Duration (days)|5|
|Vote Buffer (hours)|12|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|1,000|</a>

**Comment by GriffGreen** [comment]
Thank you for submitting @markoprljic! This was a very influential proposal, forked many times and kicked off the Hatch tribute vs Ragequit political debate!


It got 1 vote, but many forks and countless memes :-D

<img width="726" alt="Screen Shot 2021-05-13 at 10 59 10 AM" src="https://user-images.githubusercontent.com/14945613/118214812-c470dd80-b470-11eb-9733-4353401f2d91.png">

We are closing all the submissions for the next round of voting.
