### ISSUE TITLE
🔮

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/TEC-Hatch-Vote#41]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=76&maxihr=314&ihtr=3000000&ihmaxr=10000000&hor=30&hpd=21&her=1&ht=2&sr=85&maq=21&vdd=4&vbh=12&rqh=12&tfx=1000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/9e3ff604-42a9-4227-b84a-cee4217dc5ae)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/43a6dfaf-afa1-44de-a628-d2889bc8c5ae)
            
## Hatch Strategy

<p>reasonable target goal and low hatch tribute to incentivize only super value aligned hatchers to stay. Longer hatch period to allow the Trusted Seed process to happen in case interesting hatchers want to jump in and also to improve the chances of reaching the higher max goal. The IH rate is fair for both builders and backers.</p>
            
## DAO Strategy

<p>high tollgate fee to have a quality standard for the proposals that are coming (hopefully just one :)). Then also higher support required and minimum quorum because well crafted proposals make participation easier and we want to set the tone of engagement to the future of the Commons </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 3000000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 10000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 30 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 33750  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 4 days. They will require at least 85% support, and a minimum of 21% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 12 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 12 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 730 votes per year.

- To prevent griefing attacks, it will cost 1000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=76&maxihr=314&ihtr=3000000&ihmaxr=10000000&hor=30&hpd=21&her=1&ht=2&sr=85&maq=21&vdd=4&vbh=12&rqh=12&tfx=1000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,000,000|
|Maximum Goal (wxDai)|10,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|76|
|Impact Hour Rate at Infinity (wxDai/IH)|314|
|Hatch Membership Ratio (wxDai/CSTK)|30|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|2|
|Support Required (%)|85|
|Minimum Quorum (%)|21|
|Vote Duration (days)|4|
|Vote Buffer (hours)|12|
|Ragequit (hours)|12|
|Tollgate Fee (wxDai)|1,000|</a>

**Comment by liviade1** [comment]
High Quorum inspired by #37

**Comment by chuygarcia92** [comment]
I love it! Just needs a higher hatch tribute ;)

**Comment by GriffGreen** [comment]
Wow!! ^^^ Look at all those forks! not only were your parameters awesome enough to score 102 votes, but you also brought Emojis into the Titles! This was huge!

We are closing all the submissions for the next round of voting. Thank you for submitting!
