### ISSUE TITLE
May the Technocracy be Ended 🌠

### ISSUE THREAD

**Issue by marthendalnunes** [CommonsBuild/TEC-Hatch-Vote#42]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=1000000&tgihr=80&maxihr=300&ihtr=3000000&ihmaxr=15000000&hor=20&hpd=21&her=1&ht=2&sr=75&maq=15&vdd=6&vbh=6&rqh=4&tfx=2000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/58ex4g.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/2152079b-8f40-411b-bd6b-b47a035aaab0)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/82dce9ad-d5ec-4316-8466-7d1f114aa1a5)
            
## Hatch Strategy

<p>The idea is to try to decrease the friction for people putting money in, so the hatch tribute is only 2%, but I expect with that to raise more funds (3 mil target goal). 21 Days to send wxDai to the hatch seems the sweet spot between FOMO and time to reflect on the hatch. Minting rate of 1 for simplicity.</p>
            
## DAO Strategy

<p>Tollgate fee a little high just for security and having up to 4 proposals/day and 6 days of voting, so we can have a nice amount of proposal options.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 3000000 wxDai, with a minimum of 1000000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 15000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 20 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 22500  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 6 days. They will require at least 75% support, and a minimum of 15% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 4 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 6 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1460 votes per year.

- To prevent griefing attacks, it will cost 2000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=1000000&tgihr=80&maxihr=300&ihtr=3000000&ihmaxr=15000000&hor=20&hpd=21&her=1&ht=2&sr=75&maq=15&vdd=6&vbh=6&rqh=4&tfx=2000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,000,000|
|Maximum Goal (wxDai)|15,000,000|
|Minimum Goal (wxDai)|1,000,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|80|
|Impact Hour Rate at Infinity (wxDai/IH)|300|
|Hatch Membership Ratio (wxDai/CSTK)|20|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|2|
|Support Required (%)|75|
|Minimum Quorum (%)|15|
|Vote Duration (days)|6|
|Vote Buffer (hours)|6|
|Ragequit (hours)|4|
|Tollgate Fee (wxDai)|2,000|</a>

**Comment by GriffGreen** [comment]
Thank you for submitting @marthendalnunes ! This was a great proposal, getting 72 votes and a couple forks. It probably would have gotten more votes if you weren't part of the technocracy ;-)  We are closing all the submissions for the next round of voting.
