### ISSUE TITLE
Son of a Witch

### ISSUE THREAD

**Issue by ledarkdawn** [CommonsBuild/TEC-Hatch-Vote#48]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=10000000&tgihr=500&maxihr=694&ihtr=50000000&ihmaxr=100000000&hor=100&hpd=365&her=1000000&ht=25&sr=70&maq=10&vdd=10&vbh=50&rqh=1&tfx=10000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/8aeb8be1-b298-4642-ac54-622576a8b9b1)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/e3d5f186-dedf-4622-8895-00140a16bd0c)
            
## Hatch Strategy

<p>I'm just testing the parameters, nothing serious yet</p>
            
## DAO Strategy

<p>To use the defaults... Technocracy for the win</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 365 days.

- The target goal will be 50000000 wxDai, with a minimum of 10000000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 100000000 wxDai.

- Backers will need to send in 1e-06 wxDai to mint 1 TECH.

- The membership ratio is set at 100 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 112500  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 10 days. They will require at least 70% support, and a minimum of 10% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 1 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 50 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 175 votes per year.

- To prevent griefing attacks, it will cost 10000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=10000000&tgihr=500&maxihr=694&ihtr=50000000&ihmaxr=100000000&hor=100&hpd=365&her=1000000&ht=25&sr=70&maq=10&vdd=10&vbh=50&rqh=1&tfx=10000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|50,000,000|
|Maximum Goal (wxDai)|100,000,000|
|Minimum Goal (wxDai)|10,000,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|500|
|Impact Hour Rate at Infinity (wxDai/IH)|694|
|Hatch Membership Ratio (wxDai/CSTK)|100|
|Hatch Period (days)|365|
|Hatch Minting rate (TECH/wxDai)|1,000,000|
|Hatch Tribute (%)|25|
|Support Required (%)|70|
|Minimum Quorum (%)|10|
|Vote Duration (days)|10|
|Vote Buffer (hours)|50|
|Ragequit (hours)|1|
|Tollgate Fee (wxDai)|10,000|</a>

**Comment by GriffGreen** [comment]
hahahahaha OMG 10 mil min goal! you crazy man!

**Comment by GriffGreen** [comment]
This is basically like... 

"The Hatch idea sucks, let's just do an ICO with the Trusted Seed. If we don't raise 10 mil, we call it off"

**Comment by GriffGreen** [comment]
Thank you for submitting @lEscanore ! Fun proposal, despite it being a joke, it scored 13 votes!  We are closing all the submissions for the next round of voting.
