### ISSUE TITLE
8

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/TEC-Hatch-Vote#50]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=888888&tgihr=88.88&maxihr=188&ihtr=2888888&ihmaxr=8888888&hor=8&hpd=28&her=8&ht=8&sr=88&maq=8&vdd=4&vbh=8&rqh=48&tfx=1888" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![8-GIF-original-_1_](https://user-images.githubusercontent.com/14945613/117731882-28846f00-b1ef-11eb-8ae0-c7d295a31418.gif)

# Graphical Summary

![image](https://hcti.io/v1/image/5d58ada2-1bb7-485f-8ec6-b2a8b4adbbfc)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/5c4f1d70-1ae1-4492-bffa-897e77546fee)
            
## Hatch Strategy

<p>Honestly, my main goal here was to integr8 the number 8.

I think I did a good job. The Impact Hour Rate is pretty high at a low raise and relatively low at the max raise, making a nice distribution between Builders and Backers based on input, at the min raise Builders get 30% of the tokens and 13% of the token supply at Max Raise.

 
A Hatch Tribute of 8% is a nice compromise, the Ragequit % ranges between 60 and 80% so it still hurts to ragequit... but not so bad that it would never happen. 

</p>
            
## DAO Strategy

<p>I think an 8% quorum is a little high... but not unachievable, even in the annoying instances that we have to make some small votes before the big vote to do the commons upgrade.

I like a high support required, i dont want 15% of the engaged token holders to vote no on something and for it to still pass. so 88% is "Just Right"</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 28 days.

- The target goal will be 2888888 wxDai, with a minimum of 888888 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8888888 wxDai.

- Backers will need to send in 0.125 wxDai to mint 1 TECH.

- The membership ratio is set at 8 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 9000  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 4 days. They will require at least 88% support, and a minimum of 8% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 48 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 1888 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=888888&tgihr=88.88&maxihr=188&ihtr=2888888&ihmaxr=8888888&hor=8&hpd=28&her=8&ht=8&sr=88&maq=8&vdd=4&vbh=8&rqh=48&tfx=1888" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2,888,888|
|Maximum Goal (wxDai)|8,888,888|
|Minimum Goal (wxDai)|888,888|
|Impact Hour Rate at Target Goal (wxDai/IH)|88.88|
|Impact Hour Rate at Infinity (wxDai/IH)|188|
|Hatch Membership Ratio (wxDai/CSTK)|8|
|Hatch Period (days)|28|
|Hatch Minting rate (TECH/wxDai)|8|
|Hatch Tribute (%)|8|
|Support Required (%)|88|
|Minimum Quorum (%)|8|
|Vote Duration (days)|4|
|Vote Buffer (hours)|8|
|Ragequit (hours)|48|
|Tollgate Fee (wxDai)|1,888|</a>

**Comment by GriffGreen** [comment]
I like this one a lot honestly... its not a joke :-D

**Comment by JuankBell** [comment]
![giphy-downsized (5)](https://user-images.githubusercontent.com/71618349/117671662-a8b6c000-b16e-11eb-9edb-040a31aa110c.gif)

**Comment by JuankBell** [comment]
<img width="744" alt="Captura de Pantalla 2021-05-12 a la(s) 4 59 42 p  m" src="https://user-images.githubusercontent.com/71618349/118148051-ce91ce00-b3d5-11eb-85df-4259846f24e3.png">

**Comment by JuankBell** [comment]
![8-GIF-original-_2_](https://user-images.githubusercontent.com/71618349/118149058-ce460280-b3d6-11eb-84f4-d08ccd2bef77.gif)

**Comment by laurenluz** [comment]
This is actually a really awesome proposal 👀 I just have a mild resistance to all the 8s, despite all the gr8 memes

**Comment by mateodaza** [comment]
gr8 m8 I r8 this proposal an 8/8

![image](https://user-images.githubusercontent.com/18689480/118163550-bcb92680-b3e7-11eb-91e1-40f890a3b4d6.png)

if this passes with 888 votes we enter to meme heaven of DAOs

**Comment by mateodaza** [comment]
now we only need 88 votes of 1 

![image](https://user-images.githubusercontent.com/18689480/118164149-613b6880-b3e8-11eb-84e8-3bbefc2f720f.png)

**Comment by kristoferlund** [comment]
![image](https://user-images.githubusercontent.com/9698363/118190964-27984b00-b444-11eb-9be1-8160e7985fc6.png)

Boom, there it is. Taakeoff to meme heaven!

**Comment by GriffGreen** [comment]
hahaha! Well those votes were late... but honestly we should count them!

**Comment by GriffGreen** [comment]
Great proposal, got 2nd place in the "primaries" with 848 votes

**Comment by kristoferlund** [comment]
Ah, missed the 8 PM CET detail. Auto closing of token log votes would be a nice feature, together with a countdown: "Vote closes in.."

Will post feature suggestion at the Tokenlog repo.
