### ISSUE TITLE
Technocracy for the win - 🤑🤜 ✨ 🤛👷

### ISSUE THREAD

**Issue by santteegt** [CommonsBuild/TEC-Hatch-Vote#51]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=75&maxihr=150&ihtr=3200000&ihmaxr=8000000&hor=10&hpd=45&her=1&ht=5&sr=66&maq=10&vdd=3&vbh=8&rqh=24&tfx=3000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/58quz5.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/15fbaba5-57c8-4923-8d63-41789bfd194a)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/4fe8687f-9e18-4481-9157-44481db47924)
            
## Hatch Strategy

<p>
I believe that a Target raise = 4 * Min Raise is achievable and provides a good balance for builders & backers

Impact hour Rate: a competitive $75 rate at target & ~$110 at max raise seems fair and will attract more people to contribute to the TECommons

Hatch Tribute: 5% does not introduce much risk to backers

Hatch Period; 45 days to there's enough time to iterate on the Commons upgrade.
</p>
            
## DAO Strategy

<p>
A 2/3 voting support seems reasonable, while a 10% minimum quorum will allow proposals to pass if a bit more than half of builders token holders vote yes (Max Cap for builders at target goal will be ~18%)

Voting proposal buffer: enough to allow anyone in the World not to miss any unexpected voting event

Tollgate Fee: 5k wxDAI is enough skin in the game for sending proposals and will make spamming
</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 45 days.

- The target goal will be 3200000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 66% support, and a minimum of 10% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 3000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=75&maxihr=150&ihtr=3200000&ihmaxr=8000000&hor=10&hpd=45&her=1&ht=5&sr=66&maq=10&vdd=3&vbh=8&rqh=24&tfx=3000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,200,000|
|Maximum Goal (wxDai)|8,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|75|
|Impact Hour Rate at Infinity (wxDai/IH)|150|
|Hatch Membership Ratio (wxDai/CSTK)|10|
|Hatch Period (days)|45|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|5|
|Support Required (%)|66|
|Minimum Quorum (%)|10|
|Vote Duration (days)|3|
|Vote Buffer (hours)|8|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|3,000|</a>

**Comment by GriffGreen** [comment]
hahahaha great proposal @santteegt! Thank you for representing the Technocracy with great meme action! This scored 107 votes and influenced many other proposals 

We are closing all the submissions for the next round of voting.
