### ISSUE TITLE
🐙 Million $ challenge with a future

### ISSUE THREAD

**Issue by lucidcyborg** [CommonsBuild/TEC-Hatch-Vote#53]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=125&maxihr=240&ihtr=1000000&ihmaxr=5000000&hor=15&hpd=21&her=0.1&ht=30&sr=65&maq=5&vdd=3&vbh=24&rqh=48&tfx=500" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/ceeb9a71-176d-4a2f-8388-6b2a1f0713c0)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/6646de01-c691-4b51-b7fc-ccaa5513898f)
            
## Hatch Strategy
Realistic backers result outlook.
Builder incentive to make sure knowledge gathered during the hatch doesn't get lost in the future due to ragequitting
            
## DAO Strategy

<p>To use the defaults... Technocracy for the win</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 1000000 wxDai, with a minimum of 500000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 5000000 wxDai.

- Backers will need to send in 10.0 wxDai to mint 1 TECH.

- The membership ratio is set at 15 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 16875  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 65% support, and a minimum of 5% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 48 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 24 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 365 votes per year.

- To prevent griefing attacks, it will cost 500 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=125&maxihr=240&ihtr=1000000&ihmaxr=5000000&hor=15&hpd=21&her=0.1&ht=30&sr=65&maq=5&vdd=3&vbh=24&rqh=48&tfx=500" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|1,000,000|
|Maximum Goal (wxDai)|5,000,000|
|Minimum Goal (wxDai)|500,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|125|
|Impact Hour Rate at Infinity (wxDai/IH)|240|
|Hatch Membership Ratio (wxDai/CSTK)|15|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|0.1|
|Hatch Tribute (%)|30|
|Support Required (%)|65|
|Minimum Quorum (%)|5|
|Vote Duration (days)|3|
|Vote Buffer (hours)|24|
|Ragequit (hours)|48|
|Tollgate Fee (wxDai)|500|</a>

**Comment by GriffGreen** [comment]
Very focused on Builders, and a super high Hatch Tribute... Did @chuygarcia92 host your param party ;-)

**Comment by lucidcyborg** [comment]
How you guessed lol
Did my own thing tho looking forward hearing your arguments against it :D

**Comment by GriffGreen** [comment]
I saw him on the street the other day
<img width="524" alt="Screen Shot 2021-05-09 at 3 34 22 PM" src="https://user-images.githubusercontent.com/14945613/117589021-82216680-b127-11eb-89e7-46f4dc9ddf00.png">

**Comment by GriffGreen** [comment]
Thank you for submitting @mquellhorst ! This was a very fun proposal, making Chuy Proud! It scored 15 votes! We are closing all the submissions for the next round of voting.
