### ISSUE TITLE
🐙 6.9M baby

### ISSUE THREAD

**Issue by c0mput3rxz** [CommonsBuild/TEC-Hatch-Vote#54]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=80&maxihr=186&ihtr=6900000&ihmaxr=150000000&hor=25&hpd=35&her=10000&ht=19&sr=55&maq=10&vdd=7&vbh=1&rqh=3&tfx=500" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/3e57482c-555a-4139-85bc-5d5c4ef54717)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/0cb221ec-162d-4095-af19-281a8e9220c5)
            
## Hatch Strategy

<p>My hatch strategy makes it positive for developer and investors and seeks to raise between 500k and 15M with a target raise of 6.9M. The strategy provides a working developer share and locked just under 1/3 of the value in the hatch. This makes a nice balance between supporters and developers while locking value in the hatch.</p>
            
## DAO Strategy

<p>The strategy for voting allows enough time to discuss and vote on issues and provides a week voting period with 10% quorum. The tollgate fee is expensive but not unreasonable. Voting should behind soon after proposal and requires a bit over majority vote.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 35 days.

- The target goal will be 6900000 wxDai, with a minimum of 500000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 150000000 wxDai.

- Backers will need to send in 0.0001 wxDai to mint 1 TECH.

- The membership ratio is set at 25 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 28125  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 7 days. They will require at least 55% support, and a minimum of 10% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 3 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 1 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 8760 votes per year.

- To prevent griefing attacks, it will cost 500 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=80&maxihr=186&ihtr=6900000&ihmaxr=150000000&hor=25&hpd=35&her=10000&ht=19&sr=55&maq=10&vdd=7&vbh=1&rqh=3&tfx=500" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|6,900,000|
|Maximum Goal (wxDai)|150,000,000|
|Minimum Goal (wxDai)|500,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|80|
|Impact Hour Rate at Infinity (wxDai/IH)|186|
|Hatch Membership Ratio (wxDai/CSTK)|25|
|Hatch Period (days)|35|
|Hatch Minting rate (TECH/wxDai)|10,000|
|Hatch Tribute (%)|19|
|Support Required (%)|55|
|Minimum Quorum (%)|10|
|Vote Duration (days)|7|
|Vote Buffer (hours)|1|
|Ragequit (hours)|3|
|Tollgate Fee (wxDai)|500|</a>

**Comment by GriffGreen** [comment]
This is a Big Money proposal! Very focused on Backers... Builders only get 15%-1% of the total supply, i would lower the Hatch Tribute tho if we want to go for 6.9-150 mil!!!

**Comment by GriffGreen** [comment]
Thank you for submitting @c0mput3rxz ! This was a very fun proposal. It scored 13 votes! We are closing all the submissions for the next round of voting.
