### ISSUE TITLE
Params Pangea - OmniFork

### ISSUE THREAD

**Issue by mount-manu-zz** [CommonsBuild/TEC-Hatch-Vote#59]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=88.88&maxihr=200&ihtr=2000000&ihmaxr=10000000&hor=5.0&hpd=28&her=8&ht=8&sr=85&maq=8&vdd=7&vbh=8&rqh=24&tfx=2000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/58xlsp.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/442b3468-3564-40b1-95b7-b599d234fa87)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/541a4324-e422-47c9-a5cf-ed0ff1ad6da8)
            
## Hatch Strategy

<p>I went for an omnifork à la wisdom of the crowd: I’m betting that the collective intelligence of our community, distilled into votes and proposals, will be greater than the work of any single one of us.  

“Bruh, WTF?” I know, bear with me, lend me 3 minutes and I’ll explain: I gave each person the total number of votes their proposal(s) had at the time I made mine BUT, for the forked ones, I took a weighted vote number that depended on how many parameters their fork had changed from the original proposal. So, for example: Lauren’s “Goldilocks” was forked by Griff in “Goldilocks v2” by changing 8 out of the 15 parameters, or 53% of it, so I assigned him 97 votes out of the 183 total votes that his proposal had; and the remaining 86 I gave to Lauren for being the muse. Now, after calculating the weighted number of votes each person had and converting that to a % of the total votes casted at present, I equated that person’s % to a portion of the 15 parameters. This allowed me to fork several proposals simultaneously and, for the most part (with only one exception), this is how I decided how many parameter values to emulate from the people who have had the most influence on the community so far.

So, at the time I created this proposal, the stats were as follows:
Griff had 422 votes, or 34% of the 1,243 total of votes, granting him the pride — nay, the privilege! — of 5 parameter value slots within my proposal. I believe there’s a method to the madness of his latest, original proposal (titled “8”) and so I lean on him to have correctly calibrated what I consider to be the more “intricate” parameters: an IH rate of 88.88; a hatch minting rate of 8; a hatch tribute of 8%; a minimum quorum of 8%; and a vote buffer of 8 hours. 

Lauren had 297 votes, or 23%, which gives her 4 slots. The goldilocks effect got a lot of approval so I picked the values that I feel were the most representative of this notion of not-too-hot-and-not-too-cold: a target goal of 2MM; a minimum goal of 800k; and a ragequit of 24 hours.

Livia had 205 votes, or 16.49%, giving her 2 slots. Being the go-to person for anything sociocultural, I used her Hatch Membership Ratio of 30 and her Support Required value of 85% because I believe it would foster communal cohesion through DAO stakeholder activism (which would be the DAO equivalent of ‘shareholder activism’, a new vocation in and of itself IMO).

Sembrestels had 146, or 11.74%, which should’ve given him 2 slots but I only used 1 of his values: the Impact Hour Rate at Infinity of 200. I had to make an exception to my heuristic here because I don’t think a Hatch Period value of 15 days is compatible with a 2MM Target Goal given our current soft commit numbers; instead, I believe we ought to incubate for 28 days.

Vitor had 98, or 7.88%, giving him 1. I chose his Tollgate Fee of 2,000 as it seemed high enough to discourage non-serious proposals but low enough compared to the eventuality of acquiring funding from us.

Zepti, Chuy, and Tam bundled together add up to 1 slot and, since I’m pretty much making the rules here, I chose Tam’s Vote Duration of 7 days as an appropriate time for deliberation. Plus, Zepti’s Vote Buffer and Ragequit values both coincide with the ones I chose, as do Chuy’s Target Goal, Maximum Goal, Minimum Goal, and Vote Buffer values. 

I was concerned that the result of this would spiral into a conceited clusterfuck — I don’t think it did, I think it’s beautiful but if you think I need to get myself a dog, try forking my omnifork. </p>
            
## DAO Strategy

<p>The minimum goal is prudent, the target goal is ambitious but not greedy, and the IH rate at Target Goal is juicy like Notorious: that ought to be a persuasive combination of circumstances for all of us to become even more industrious and resourceful than we have been so far.

A hatch period of 4 weeks is enough for us to succeed, specially if we systematize both our onboarding and our fundraising with all the media assets we’ve been developing, which we’re already in the process of doing. 

The Hatch Membership Ratio is generous so that contributors are not capped from investing a substantial amount of money, and this in turn would make it easier for us to reach our target goal. 

The long Vote Duration is congruent with the high Support Required and both of these seem somewhat in sync with the Tollgate Fee. 
</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 28 days.

- The target goal will be 2000000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 10000000 wxDai.

- Backers will need to send in 0.125 wxDai to mint 1 TECH.

- The membership ratio is set at 5.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 5625  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 7 days. They will require at least 85% support, and a minimum of 8% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 2000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=88.88&maxihr=200&ihtr=2000000&ihmaxr=10000000&hor=5.0&hpd=28&her=8&ht=8&sr=85&maq=8&vdd=7&vbh=8&rqh=24&tfx=2000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2,000,000|
|Maximum Goal (wxDai)|10,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|88.88|
|Impact Hour Rate at Infinity (wxDai/IH)|200|
|Hatch Membership Ratio (wxDai/CSTK)|5.0|
|Hatch Period (days)|28|
|Hatch Minting rate (TECH/wxDai)|8|
|Hatch Tribute (%)|8|
|Support Required (%)|85|
|Minimum Quorum (%)|8|
|Vote Duration (days)|7|
|Vote Buffer (hours)|8|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|2,000|</a>

**Comment by GriffGreen** [comment]
Thank you for submitting @mount-manu ! This was a very interesting proposal. Getting 9th place and 207 votes and setting the stage early for the idea of using data aggregation with human sense making to find a proposal for everyone to like.  We are closing all the submissions for the next round of voting.
