### ISSUE TITLE
Vote for my first test params, if you dare

### ISSUE THREAD

**Issue by cranders1** [CommonsBuild/TEC-Hatch-Vote#6]
<h1>Parameters</h1>

| Parameters                          |   Values |
|:------------------------------------|---------:|
| Target raise (wxDai)                |   500000 |
| Maximum raise (wxDai)               |  1000000 |
| Minimum raise (wxDai)               |   150000 |
| Impact hour slope (wxDai/IH)        |     2601 |
| Maximum impact hour rate (wxDai/IH) |     1000 |
| Hatch oracle ratio (wxDai/CSTK)     |      100 |
| Hatch period (days)                 |       14 |
| Hatch exchange rate (TECH/wxDai)    |     1000 |
| Hatch tribute (%)                   |        5 |
| Support required (%)                |       51 |
| Minimum accepted quorum (%)         |       20 |
| Vote duration (days)                |       14 |
| Vote buffer (hours)                 |       24 |
| Rage quit (hours)                   |       12 |
| Tollgate fee (wxDai)                |      500 |
            
<h1>Results</h1>

<p>craig test1
eyeing $20 IH rate
60/40 redeem/culture - seems off</p>

- It costs 500 wxDai to make a proposal.

- Votes will be voted on for 14 days.

- TECH token holders will have 12 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There will be a minimum of 24 hours between proposals so people can exit safely in weird edge case scenarios.

- A proposal that passes can be executed 36 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 200000 wxDai to the Hatch.

Play with my parameters [here](https://params.tecommons.org/hatch?ihminr=150000&hs=2601&maxihr=1000&ihtr=500000&ihmaxr=1000000&hor=100&hpd=14&her=1000&ht=5&sr=51&maq=20&vdd=14&vbh=24&rqh=12&tfx=500).

To see the value of your individual Impact Hours, click [here to go to the Hatch Config Dashboard with these parameters](https://params.tecommons.org/hatch?ihminr=150000&hs=2601&maxihr=1000&ihtr=500000&ihmaxr=1000000&hor=100&hpd=14&her=1000&ht=5&sr=51&maq=20&vdd=14&vbh=24&rqh=12&tfx=500) and explore the Impact Hour Results table.
            

<h1>Output Charts</h1>

![image](https://hcti.io/v1/image/52cd1423-c685-4f09-b912-1d41a2a6cb1f)

<h1>Output Scenarios</h1>

![image](https://hcti.io/v1/image/6b47115d-9a38-462b-bdd4-7ea93b31e2c0)

**Comment by cranders1** [comment]
Nice @GriffGreen 
Slated for closing (test garbage), but Griff easily forked it using the super easy load param set link embedded in each issue.
Whoop.

**Comment by GriffGreen** [comment]
@cranders1 YEP I am closing this cause it is using the old Impact hour slope... if you want to resubmit, click the link up there as you would to fork it... It will look screwed up... but if you note the Impact Hour Rate at the Target goal here and add that in, it should work
