### ISSUE TITLE
118 - Chuy's Greatest Hits (Fork of #50 aka 8)

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/TEC-Hatch-Vote#60]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=888888&tgihr=118.88&maxihr=188&ihtr=2888888&ihmaxr=8888888&hor=8.0&hpd=28&her=0.08&ht=8&sr=88&maq=8&vdd=8&vbh=8&rqh=18&tfx=1888.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/58pamu.jpg) 

# Graphical Summary

![image](https://hcti.io/v1/image/97361063-633a-435f-82cd-eb4407f41c78)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/fa2c0f46-b98e-4e4e-817d-a9401b929b94)
            
## Hatch Strategy

<p>This is a summary of what I've learned spending some weeks now playing around with the dashboard. I really liked 8 (#50) but I would choose to be more rewarding with the builders if the minimum goal is reached. I also brought the Hatch minting rate down, since I like this psychology around the token value better</p>
            
## DAO Strategy

<p>I brought the ragequit hours down, everything else is the same as the original 8</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 28 days.

- The target goal will be 2888888 wxDai, with a minimum of 888888 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8888888 wxDai.

- Backers will need to send in 12.5 wxDai to mint 1 TECH.

- The membership ratio is set at 8.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 9000  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 8 days. They will require at least 88% support, and a minimum of 8% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 18 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 1888.0 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=888888&tgihr=118.88&maxihr=188&ihtr=2888888&ihmaxr=8888888&hor=8.0&hpd=28&her=0.08&ht=8&sr=88&maq=8&vdd=8&vbh=8&rqh=18&tfx=1888.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2,888,888|
|Maximum Goal (wxDai)|8,888,888|
|Minimum Goal (wxDai)|888,888|
|Impact Hour Rate at Target Goal (wxDai/IH)|118.88|
|Impact Hour Rate at Infinity (wxDai/IH)|188|
|Hatch Membership Ratio (wxDai/CSTK)|8.0|
|Hatch Period (days)|28|
|Hatch Minting rate (TECH/wxDai)|0.08|
|Hatch Tribute (%)|8|
|Support Required (%)|88|
|Minimum Quorum (%)|8|
|Vote Duration (days)|8|
|Vote Buffer (hours)|8|
|Ragequit (hours)|18|
|Tollgate Fee (wxDai)|1,888.0|</a>

**Comment by GriffGreen** [comment]
Backers will need to send in 12.5 wxDai to mint 1 TECH.

What were your thoughts there? 100 wxDai for 8 Hatch tokens?

**Comment by chuygarcia92** [comment]
My final proposal is #79
