### ISSUE TITLE
APPCD - Aesthetically Pleasing Pie Chart Divisions (Fork of #37 but not really)

### ISSUE THREAD

**Issue by prohg** [CommonsBuild/TEC-Hatch-Vote#61]
## APPCD - Aesthetically Pleasing Pie Chart Divisions (Fork of #37 but not really) <a href="https://params.tecommons.org/hatch?ihminr=1000000&tgihr=152&maxihr=200.0&ihtr=3000000&ihmaxr=6000000&hor=10.0&hpd=30&her=1.0&ht=25&sr=85&maq=15&vdd=7&vbh=12&rqh=24&tfx=1000.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/86e965b2-5f30-422b-8649-38c652f08fa1)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/371ef517-9943-44a2-86a0-b0c60c4e6639)
            
## Hatch Strategy

<p>Hatch tribute set to 25% to incentivize participants to voice their opinions and collaborate towards proposals that benefit everyone. I mostly went with these params because I like that at the target goal, redeemability gets divided into 2/4 for backers, 1/4 for builders and the other 1/4 as non redeemable. On the minimum goal graphic we can see there's an equal split between builders and backers - on the maximum goal backers get a bigger piece of the pie chart.</p>
            
## DAO Strategy

<p>tried striking a balance between @liviade1 's Crystal Ball proposal (https://github.com/CommonsBuild/TEC-Hatch-Vote/issues/41) and @GriffGreen 's fork of it (https://github.com/CommonsBuild/TEC-Hatch-Vote/issues/47) since I agree w their logic. Vote duration was set to a week so its easy to remember, same logic was applied to the ragequit delay but its one day instead. </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 30 days.

- The target goal will be 3000000 wxDai, with a minimum of 1000000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 6000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 10.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 7 days. They will require at least 85% support, and a minimum of 15% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 12 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 730 votes per year.

- To prevent griefing attacks, it will cost 1000.0 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=1000000&tgihr=152&maxihr=200.0&ihtr=3000000&ihmaxr=6000000&hor=10.0&hpd=30&her=1.0&ht=25&sr=85&maq=15&vdd=7&vbh=12&rqh=24&tfx=1000.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,000,000|
|Maximum Goal (wxDai)|6,000,000|
|Minimum Goal (wxDai)|1,000,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|152|
|Impact Hour Rate at Infinity (wxDai/IH)|200.0|
|Hatch Membership Ratio (wxDai/CSTK)|10.0|
|Hatch Period (days)|30|
|Hatch Minting rate (TECH/wxDai)|1.0|
|Hatch Tribute (%)|25|
|Support Required (%)|85|
|Minimum Quorum (%)|15|
|Vote Duration (days)|7|
|Vote Buffer (hours)|12|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|1,000.0|</a>

**Comment by GriffGreen** [comment]
This is awesome hahahaha very builder heavy

**Comment by GriffGreen** [comment]
Thank you for submitting @prohg ! This was probably the most beautiful proposal submitted and it scored 20 votes! We are closing all the submissions for the next round of voting.
