### ISSUE TITLE
You better raise some funds.

### ISSUE THREAD

**Issue by natenatesoo** [CommonsBuild/TEC-Hatch-Vote#62]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=70&maxihr=930&ihtr=2500000&ihmaxr=9000000&hor=4&hpd=25&her=1&ht=4&sr=80&maq=5&vdd=12&vbh=5&rqh=36&tfx=2500" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/0c608438-b4af-4418-b2ce-b18af2b3bde9)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/7e4edcd0-a3eb-4df6-8e78-d663efc2a9e1)
            
## Hatch Strategy

<p>Low Impact Hour Rate at Minimum to incentivize Raise.

Very High Impact Hour Rate at Target, and Max. 

Low Hatch Tribute to provide flexibility for large backers.

Low Hatch Minting Rate  </p>
            
## DAO Strategy

<p>Moderate Support Required, Low Minimum Quorum.

Shorter Vote Duration, and High Rage Quit Delay.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 25 days.

- The target goal will be 2500000 wxDai, with a minimum of 500000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 9000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 4 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 4500  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 12 days. They will require at least 80% support, and a minimum of 5% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 36 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 5 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1752 votes per year.

- To prevent griefing attacks, it will cost 2500 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=70&maxihr=930&ihtr=2500000&ihmaxr=9000000&hor=4&hpd=25&her=1&ht=4&sr=80&maq=5&vdd=12&vbh=5&rqh=36&tfx=2500" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2,500,000|
|Maximum Goal (wxDai)|9,000,000|
|Minimum Goal (wxDai)|500,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|70|
|Impact Hour Rate at Infinity (wxDai/IH)|930|
|Hatch Membership Ratio (wxDai/CSTK)|4|
|Hatch Period (days)|25|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|4|
|Support Required (%)|80|
|Minimum Quorum (%)|5|
|Vote Duration (days)|12|
|Vote Buffer (hours)|5|
|Ragequit (hours)|36|
|Tollgate Fee (wxDai)|2,500|</a>

**Comment by GriffGreen** [comment]
Great Proposal @natenatesoo! This was a very novel proposal. Actually similar to #65 with a very high IH Rate at infinity! This makes for a relatively stable share of governance power between the Builders and Backers. An important variant of this configuration space! It scored 52 votes.

We are closing all the submissions for the next round of voting.
