### ISSUE TITLE
Summoning The Technocracy - 🫀🫀🫀👹👹👹👽👽👽👾 🤖👾 🤖👾 🤖🤜 ✨ 🤛👷

### ISSUE THREAD

**Issue by LinuxIsCool** [CommonsBuild/TEC-Hatch-Vote#63]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=75.0&maxihr=150.0&ihtr=3200000&ihmaxr=8000000&hor=10.0&hpd=45&her=5.343777245&ht=5&sr=66&maq=10&vdd=3&vbh=8&rqh=72&tfx=666" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

<a href="https://imgflip.com/i/591yru"><img src="https://i.imgflip.com/591yru.jpg" title="made at imgflip.com"/></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

# Graphical Summary

![image](https://hcti.io/v1/image/a214a972-0f9e-4314-94d2-9ccccabe329d)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/b8df37e6-5ac5-4cbc-9b35-8a01281e12cb)
            
## Hatch Strategy

Forked from: https://github.com/CommonsBuild/TEC-Hatch-Vote/issues/51 

### Summoning the Technocracy

My strategy is inspired by santteegt.eth, the technocracy overlord of web3. Let the technocracy reign! Technocracies built crypto! Technocracies built web3! Technocracies built the internet! Technocracies are the way. Let them reign for 1000 years.

Santiago's idea to implement technocratic parameters is wonderful. I have improved upon it slightly in three ways.

1. Modified the Hatch Minting Rate so that there will be 21million tokens minted in the case that the target goal is met and in honour of our lord Satoshi of the underworld.
            
## DAO Strategy

2. Increase RageQuit Delay hours to be 3 days, just because I think that gives backers better safety

3. Reduce the tollgate fee to 666 so that it's not so expensive to put forward proposals and also to worship our dark lord Satoshi of the underworld.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 45 days.

- The target goal will be 3200000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8000000 wxDai.

- Backers will need to send in 0.18713354882740812 wxDai to mint 1 TECH.

- The membership ratio is set at 10.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 66% support, and a minimum of 10% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 72 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 666 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=75.0&maxihr=150.0&ihtr=3200000&ihmaxr=8000000&hor=10.0&hpd=45&her=5.343777245&ht=5&sr=66&maq=10&vdd=3&vbh=8&rqh=72&tfx=666" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,200,000|
|Maximum Goal (wxDai)|8,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|75.0|
|Impact Hour Rate at Infinity (wxDai/IH)|150.0|
|Hatch Membership Ratio (wxDai/CSTK)|10.0|
|Hatch Period (days)|45|
|Hatch Minting rate (TECH/wxDai)|5.343777245|
|Hatch Tribute (%)|5|
|Support Required (%)|66|
|Minimum Quorum (%)|10|
|Vote Duration (days)|3|
|Vote Buffer (hours)|8|
|Ragequit (hours)|72|
|Tollgate Fee (wxDai)|666|</a>

**Comment by GriffGreen** [comment]
666 tollgate fee 🤣

**Comment by GriffGreen** [comment]
As part of the Technocracy, I love the 45 day hatch period :-D 

I also like the equal time voting and ragequit delay... thats how Molochv1 was as well.

**Comment by GriffGreen** [comment]
Thank you for submitting @LinuxIsCool ! This was a very fun proposal. It cracked the top 10 for proposals getting 188 votes, representing the Technocracy 👹  We are closing all the submissions for the next round of voting.
