### ISSUE TITLE
Balanced Parameters for the Indecisive Token Economist. 

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/TEC-Hatch-Vote#64]
![image](https://user-images.githubusercontent.com/67759413/117747897-041f9700-b1dd-11eb-8425-5945b7222a98.png)
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=400000&tgihr=85.0&maxihr=154&ihtr=3000000&ihmaxr=8000000&hor=10&hpd=21&her=1&ht=7.5&sr=75&maq=8&vdd=5&vbh=16&rqh=25&tfx=777" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/d32b450f-83ac-47fb-9186-449d992dc44e)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/df0d9a0a-3069-43c4-93b5-891b17c4b8a3)
            
## Hatch Strategy

<p>I lowered the impact hour rate for hitting min goal but if we hit the max or target goal the impact hour rate will be much more interesting. It's important also to keep a straight forward minting rate 1 wxdai = 1 TECH forever and always</p>
            
## DAO Strategy

<p>I wanted a good balance for quorum and medium support required to allow voting to be easy enough with a steady troll rate of 48 TECH per hour. Rage quitting is important that we have enough time to see decisions made, considering people might not have 100% of their focus on checking the status of votes.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 3000000 wxDai, with a minimum of 400000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 5 days. They will require at least 75% support, and a minimum of 8% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 25 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 16 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 547 votes per year.

- To prevent griefing attacks, it will cost 777 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=400000&tgihr=85.0&maxihr=154&ihtr=3000000&ihmaxr=8000000&hor=10&hpd=21&her=1&ht=7.5&sr=75&maq=8&vdd=5&vbh=16&rqh=25&tfx=777" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,000,000|
|Maximum Goal (wxDai)|8,000,000|
|Minimum Goal (wxDai)|400,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|85.0|
|Impact Hour Rate at Infinity (wxDai/IH)|154|
|Hatch Membership Ratio (wxDai/CSTK)|10|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|7.5|
|Support Required (%)|75|
|Minimum Quorum (%)|8|
|Vote Duration (days)|5|
|Vote Buffer (hours)|16|
|Ragequit (hours)|25|
|Tollgate Fee (wxDai)|777|</a>

**Comment by GriffGreen** [comment]
Great proposal @divine-comedian I think there is some latent discrimination against the meme... the USSR gets a bad rap but despite that it scored 39 votes!

We are closing all the submissions for the next round of voting.
