### ISSUE TITLE
🧙‍♂️🧙‍♂️

### ISSUE THREAD

**Issue by mendesfabio** [CommonsBuild/TEC-Hatch-Vote#66]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=50&maxihr=250&ihtr=1000000&ihmaxr=3000000&hor=10&hpd=21&her=1&ht=20&sr=75&maq=5&vdd=3&vbh=8&rqh=24&tfx=1500" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/503d021b-f63a-41fa-b394-f085b5c89031)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/3efe399a-daba-46fc-a5b0-ce524ac56141)
            
## Hatch Strategy

<p>1M Target Goal! 1 xDai = 1 TECH! Hatch ftw!</p>
            
## DAO Strategy

<p>I increased the Tollgate Fee to prevent griefing attacks. I feel that a proposal voted for 3 days + 1 day of Ragequit Delay is reasonable. Also, 3/4 of support required just looks right! :D </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 21 days.

- The target goal will be 1000000 wxDai, with a minimum of 500000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 3000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 75% support, and a minimum of 5% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 1500 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=50&maxihr=250&ihtr=1000000&ihmaxr=3000000&hor=10&hpd=21&her=1&ht=20&sr=75&maq=5&vdd=3&vbh=8&rqh=24&tfx=1500" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|1,000,000|
|Maximum Goal (wxDai)|3,000,000|
|Minimum Goal (wxDai)|500,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|50|
|Impact Hour Rate at Infinity (wxDai/IH)|250|
|Hatch Membership Ratio (wxDai/CSTK)|10|
|Hatch Period (days)|21|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|20|
|Support Required (%)|75|
|Minimum Quorum (%)|5|
|Vote Duration (days)|3|
|Vote Buffer (hours)|8|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|1,500|</a>

**Comment by GriffGreen** [comment]
wow pretty low max goal and a high tribute! Pretty cool proposal! A nice option for @chuygarcia92 and the ProTribute contingent.

I would suggest we lower the CSTK ratio tho for the final round if this gets voted in, to match the low cap and avoid a race to ape in.

**Comment by GriffGreen** [comment]
Thank you for submitting @mendesfabio ! This was a great proposal and scored 5 votes! We are closing all the submissions for the next round of voting.
