### ISSUE TITLE
Vote for My Params

### ISSUE THREAD

**Issue by dekanbro** [CommonsBuild/TEC-Hatch-Vote#68]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=100&maxihr=100&ihtr=888888&ihmaxr=1000000&hor=5&hpd=2&her=1&ht=10&sr=51&maq=1&vdd=3&vbh=1&rqh=2&tfx=100" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/26d70e1f-4515-498f-9137-a706ae589a05)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/34780dc2-f06b-4a48-8b77-a47df6b86119)
            
## Hatch Strategy

<p>Raise a max of 1mil with a target of 888,888. This is build to start a bootstrap round of building. Test thesis in the real world and keep people involved over this bootstrap phase. Keep the raise manageable and fair to bootstrap to another round in the future. 
Should keep a 20% burn rate per month, so contributors can keep track of progress and watch for funny business.
10% fee on early exits but diamond hands should recoup the 10% paid in tokens at the end of the round.
Short Hatch period to increase FOMO and get right to buidling</p>
            
## DAO Strategy

<p>51% of total votes should be yes, only takes one vote to pass. This reduces coordination costs because most onchain proposals will be decided off chain first with soft consensus. It only takes one so voting yes is not important unless some votes no.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 2 days.

- The target goal will be 888888 wxDai, with a minimum of 500000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 1000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 5 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 5625  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 51% support, and a minimum of 1% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 2 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 1 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 8760 votes per year.

- To prevent griefing attacks, it will cost 100 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=500000&tgihr=100&maxihr=100&ihtr=888888&ihmaxr=1000000&hor=5&hpd=2&her=1&ht=10&sr=51&maq=1&vdd=3&vbh=1&rqh=2&tfx=100" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|888,888|
|Maximum Goal (wxDai)|1,000,000|
|Minimum Goal (wxDai)|500,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|100|
|Impact Hour Rate at Infinity (wxDai/IH)|100|
|Hatch Membership Ratio (wxDai/CSTK)|5|
|Hatch Period (days)|2|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|10|
|Support Required (%)|51|
|Minimum Quorum (%)|1|
|Vote Duration (days)|3|
|Vote Buffer (hours)|1|
|Ragequit (hours)|2|
|Tollgate Fee (wxDai)|100|</a>

**Comment by GriffGreen** [comment]
Thank you for submitting @dekanbro ! This was a very nice first proposal. 
It scored 20 votes! And I for one LOVE the 1 hour vote proposal buffer!   

We are closing all the submissions for the next round of voting.
