### ISSUE TITLE
DURGADAS: PARAMS FOR HODLrS and BUIDLERS!

### ISSUE THREAD

**Issue by durgadasji** [CommonsBuild/TEC-Hatch-Vote#69]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=450000&tgihr=90&maxihr=250&ihtr=3000000&ihmaxr=8000000&hor=5&hpd=28&her=0.01&ht=12&sr=78&maq=5&vdd=4&vbh=12&rqh=48&tfx=800.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![595y8g](https://user-images.githubusercontent.com/4055243/117893605-953f4e00-b26f-11eb-9006-de41b71a56e8.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/6185815f-f62b-438c-b257-46e9a5db1952)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/889a144d-f71c-4741-857c-8f3e7acff656)
            
## Hatch Strategy

<p>I like Zep's approach, but I wanted MOAR HODLing and MOAR for Builders and the folks who have been here for a while.</p>
            
## DAO Strategy

<p>I wanted to tweak it up a little to reward the Cultural Build participants without disincentivizing investment, but preventing ragequitting with slightly longer timeframes for this, since those who have been around building will be more likely to stick around. </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 28 days.

- The target goal will be 3000000 wxDai, with a minimum of 450000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8000000 wxDai.

- Backers will need to send in 100.0 wxDai to mint 1 TECH.

- The membership ratio is set at 5 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 5625  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 4 days. They will require at least 78% support, and a minimum of 5% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 48 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 12 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 730 votes per year.

- To prevent griefing attacks, it will cost 800.0 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=450000&tgihr=90&maxihr=250&ihtr=3000000&ihmaxr=8000000&hor=5&hpd=28&her=0.01&ht=12&sr=78&maq=5&vdd=4&vbh=12&rqh=48&tfx=800.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|3,000,000|
|Maximum Goal (wxDai)|8,000,000|
|Minimum Goal (wxDai)|450,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|90|
|Impact Hour Rate at Infinity (wxDai/IH)|250|
|Hatch Membership Ratio (wxDai/CSTK)|5|
|Hatch Period (days)|28|
|Hatch Minting rate (TECH/wxDai)|0.01|
|Hatch Tribute (%)|12|
|Support Required (%)|78|
|Minimum Quorum (%)|5|
|Vote Duration (days)|4|
|Vote Buffer (hours)|12|
|Ragequit (hours)|48|
|Tollgate Fee (wxDai)|800.0|</a>

**Comment by GriffGreen** [comment]
Fork of https://github.com/CommonsBuild/TEC-Hatch-Vote/issues/57 with a higher Hatch Tribute!!

**Comment by GriffGreen** [comment]
Fantastic proposal @durgadasji ! Thank you for submitting and MEMEING! :-D Gotta get you and the Spiral Dynamics crew to come to a meme party some time ;-)

This scored 33 votes... nice number :-D

We are closing all the submissions for the next round of voting.
