### ISSUE TITLE
420 / 69

### ISSUE THREAD

**Issue by BradleyC** [CommonsBuild/TEC-Hatch-Vote#70]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=420069&tgihr=69&maxihr=420&ihtr=1420069&ihmaxr=69420069&hor=6.9&hpd=42&her=0.69&ht=6.9&sr=69&maq=42&vdd=4&vbh=4&rqh=69&tfx=420" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/5977k2.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/20a3bf4a-a8c6-46c8-8bec-e9a06ef5a65a)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/eaa69f52-3f77-4225-b979-ab9f9d2abea2)
            
## Hatch Strategy

<p>420 / 69, need I say more??</p>
            
## DAO Strategy

<p>The high quorum threshold will require a consistently active membership. I suggest passing a pipe in order to ensure attendance.

Because high participation is required, and the time frame to submit is narrow, tollgate fee is lowered below default.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 4.20 days.

- The target goal will be 1420069 wxDai, with a minimum of 420069 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 69420069 wxDai.

- Backers will need to send in 1.4492753623188408 wxDai to mint 1 TECH.

- The membership ratio is set at 6.9 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 7762  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 4 days. They will require at least 69% support, and a minimum of 42% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 69 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 4.20 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 2190 votes per year.

- To prevent griefing attacks, it will cost 420 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=420069&tgihr=69&maxihr=420&ihtr=1420069&ihmaxr=69420069&hor=6.9&hpd=42&her=0.69&ht=6.9&sr=69&maq=42&vdd=4&vbh=4&rqh=69&tfx=420" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|1,420,069|
|Maximum Goal (wxDai)|69,420,069|
|Minimum Goal (wxDai)|420,069|
|Impact Hour Rate at Target Goal (wxDai/IH)|69|
|Impact Hour Rate at Infinity (wxDai/IH)|420|
|Hatch Membership Ratio (wxDai/CSTK)|6.9|
|Hatch Period (days)|42.0|
|Hatch Minting rate (TECH/wxDai)|0.69|
|Hatch Tribute (%)|6.9|
|Support Required (%)|69|
|Minimum Quorum (%)|42|
|Vote Duration (days)|4.20|
|Vote Buffer (hours)|4.20|
|Ragequit (hours)|69|
|Tollgate Fee (wxDai)|420|</a>

**Comment by tamarandom** [comment]
That meme though! 😂  😂  😂

**Comment by GriffGreen** [comment]
hahahahaha omg! What a Great MEME!

Thank you for submitting @BradleyC ! Your proposal scored 10 motes! Meme driven economic design is likely the future of finance ;-D We are closing all the submissions for the next round of voting.
