### ISSUE TITLE
Sustainable Community Pooled Bits and Bytes

### ISSUE THREAD

**Issue by marcodarko1** [CommonsBuild/TEC-Hatch-Vote#71]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=1280000&tgihr=64&maxihr=128&ihtr=2560000&ihmaxr=7680000&hor=16&hpd=32&her=1&ht=8&sr=64&maq=16&vdd=4&vbh=16&rqh=32&tfx=128" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/90069f4e-f9b2-454d-b486-b3a35dfe70f0)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/665d2727-c9c5-4f7e-8da4-965042f19b47)
            
## Hatch Strategy

<p>Composable Community Pooled Resource (CPR) inspired by bits and bytes (8, 64, 128, 256, 512, 768) and aiming to optimize temporal states (past, present, and future, for a sustainable community . 
In short, this proposal tried to find communal equilibrium with the following attributes: 
•	Modest impact hour rate at Target Goal that doubles at Infinity 
•	Balancing between compensating past work (i.e. Impact Hours) and securing funds for future building. 
•	Moderate Hatch Tribute 8% as a transfer to the community pooled resources and stability mechanism. 
•	Target goal (2.56 Million) is double the minimum goal (1.28 Million) and Maximum Goal (7.68 Million) has a ratio of 1:6 between Min and Max. 
•	Membership Ratio set at 16 to incentivize hatch commitment funding pooled from CSTK holders
</p>
            
## DAO Strategy

<p>Voting Strategy is to incentivize active participation by the community and consensus around proposals using a clear and convincing standard consensus. Attributes are: 
•	Modest quourum to incentivize community participation and validate community actions through consensus
•	Low tollgate fees. Enough to disincentivize spamming but low enough to not create high barriers for community members to bring issues for communal vote.
•	32 hour cooling off period so that before a RageQuit there is sufficient time to sleep on decision to leave the community. 
•	Vote delay is long enough that would avoid only falling on a weekend. </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 32 days.

- The target goal will be 2560000 wxDai, with a minimum of 1280000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 7680000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 16 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 18000  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 4 days. They will require at least 64% support, and a minimum of 16% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 32 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 16 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 547 votes per year.

- To prevent griefing attacks, it will cost 128 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=1280000&tgihr=64&maxihr=128&ihtr=2560000&ihmaxr=7680000&hor=16&hpd=32&her=1&ht=8&sr=64&maq=16&vdd=4&vbh=16&rqh=32&tfx=128" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2,560,000|
|Maximum Goal (wxDai)|7,680,000|
|Minimum Goal (wxDai)|1,280,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|64|
|Impact Hour Rate at Infinity (wxDai/IH)|128|
|Hatch Membership Ratio (wxDai/CSTK)|16|
|Hatch Period (days)|32|
|Hatch Minting rate (TECH/wxDai)|1|
|Hatch Tribute (%)|8|
|Support Required (%)|64|
|Minimum Quorum (%)|16|
|Vote Duration (days)|4|
|Vote Buffer (hours)|16|
|Ragequit (hours)|32|
|Tollgate Fee (wxDai)|128|</a>

**Comment by GriffGreen** [comment]
Thank you for submitting @marcodarko1! This was a very well constructed proposal! Getting an auspicious 111 votes (needed 17 more for that nice round 128!)  We are closing all the submissions for the next round of voting.
