### ISSUE TITLE
The final Vote-down!!! 💪🚀✨

### ISSUE THREAD

**Issue by PabloCGL** [CommonsBuild/TEC-Hatch-Vote#75]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=400000&tgihr=80.0&maxihr=200.0&ihtr=2400000&ihmaxr=8000000&hor=25.0&hpd=28&her=1.0&ht=7&sr=80&maq=10&vdd=5&vbh=8&rqh=48&tfx=5000.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![final-votedown](https://user-images.githubusercontent.com/50929773/118045220-e9cdf080-b377-11eb-9c14-a34bc62de9e1.png)

# Graphical Summary

![image](https://hcti.io/v1/image/5489ff59-ed9a-456f-80ae-03aa77913c13)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/0e9c1d4b-7b15-4868-9b48-4421c432057d)
            
## Hatch Strategy

<p>Self-fork of #55, but with adjustments after some great discussions at the param parties/debates. Hatch Strategy stays the same (low min goal, moderatly high membership ratio, middle-of-the-road tribute), I only modified the voting params.</p>
            
## DAO Strategy

<p>I basically got convinced that higher required support is the way to go. Voting "no" instead of just abstaining is a pretty strong signal and that should be taken into account.
I also lowered the proposal buffer for the case there is a situation where we NEED to pass proposals. The tollgate stays high to avoid spamming, though. </p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 28 days.

- The target goal will be 2400000 wxDai, with a minimum of 400000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 8000000 wxDai.

- Backers will need to send in 1.0 wxDai to mint 1 TECH.

- The membership ratio is set at 25.0 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 28125  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 5 days. They will require at least 80% support, and a minimum of 10% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 48 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 5000.0 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=400000&tgihr=80.0&maxihr=200.0&ihtr=2400000&ihmaxr=8000000&hor=25.0&hpd=28&her=1.0&ht=7&sr=80&maq=10&vdd=5&vbh=8&rqh=48&tfx=5000.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|2,400,000|
|Maximum Goal (wxDai)|8,000,000|
|Minimum Goal (wxDai)|400,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|80.0|
|Impact Hour Rate at Infinity (wxDai/IH)|200.0|
|Hatch Membership Ratio (wxDai/CSTK)|25.0|
|Hatch Period (days)|28|
|Hatch Minting rate (TECH/wxDai)|1.0|
|Hatch Tribute (%)|7|
|Support Required (%)|80|
|Minimum Quorum (%)|10|
|Vote Duration (days)|5|
|Vote Buffer (hours)|8|
|Ragequit (hours)|48|
|Tollgate Fee (wxDai)|5,000.0|</a>

**Comment by GriffGreen** [comment]
Wow! Last minute proposal with A LOT of votes!!! Great piece of Token Engineering! 7th place scoring 272 votes!

**Comment by GriffGreen** [comment]
Closing all the issues for the next round
