### ISSUE TITLE
Easy like Sunday morning 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/TEC-Hatch-Vote#76]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=400000&tgihr=80.0&maxihr=200.0&ihtr=1000000&ihmaxr=15000000&hor=50&hpd=28&her=12&ht=7&sr=80&maq=10&vdd=4&vbh=8&rqh=48&tfx=5000.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/39c278b3-5928-417a-b158-b1f71ff68073)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/68aac052-f3b3-4b63-abee-bb59eef77b31)
            
<p>Tweak on #52 (mine) which is a fork of #32 (Nuggin’s)
</p>

## Hatch Strategy

My original rationale is pasted below. It still stands but now with these adjustments.
Hatch minting rate changed to 12 to produce 21 million total tokens at the target goal; a nod to Bitcoin.  

I have been thinking about whether or not to drop the membership ratio and, in the end, I’m leaving it at 50x. This would cap anyone who just joined the Trusted Seed at about 1 BTC, which provides a nice symmetry to 21 million tokens. 

--- original rationale from #52 ---
In appreciations of Nuggan’s raise-a-lot, I’m forking #32.

For the goals, I’d like the min to be within what I will call a “certainty” zone so I’m setting it to what we have in soft commitments we have after having done 1-1 sessions with 90+ hatchers. Failure to reach the min goal will really knock the wind out of our momentum sail. I’m good with a super high max so leaving that as is though I’m dropping the target to something that feels reachable to me.

I tweaked the IH rates because the outputs make more sense to me with the target raise that I selected. The min results in ~42/IH and the target would be about 80/IH. Also, the builders have a larger share of the pie at the min goal but then the backers have a larger share at the target. That seems right. I’m not even looking at the max raise since I am going with a pie-in-the-sky figure.

I like what Nuggan’s done with a high mem ratio and high tribute. Essentially, sure you’re welcome in but if you come in, stay in. ;)

For the Hatch period, I lean toward longer though I can also see the advantages of a shorter period. In the end, I choose 4 weeks. Enough time for everyone that wants to to get in but not so long that it drags on.
---

            
## DAO Strategy

For this part, I made the following changes:

Raised the minimum support to 80%, persuaded by the “no” votes argument. It does indeed seem less than ideal that a proposal could pass even if 40% of Hatchers vote “no”. I’m settling on 80/20. 

Lowered the vote proposal buffer to 6 hours. As we are not actually expecting many votes, there are very few cases where this should play out. Spam, but we will have a high tollgate to deter that. And emergency patches, where time matters so 4 proposals over a 24 hour period should cover that latter case. 

Lowered the vote duration to 4 days. I just can’t go lower than that. I tried to type “3” but kept deleting it.

--- original rationale from #52 ---
I like Nuggan’s rationale for 60% support and 10% quorum. I wonder how difficult these may be to reach in real life but I am still going to choose the same.
I’m going with a higher proposal buffer (thinking we should have very, very few proposals) and a much higher tollgate to discourage frivolity but not so high that it will be a barrier. And I'm giving a little more time for a more thoughtful ragequit. ;)
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 28 days.

- The target goal will be 1000000 wxDai, with a minimum of 400000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 15000000 wxDai.

- Backers will need to send in 0.08333333333333333 wxDai to mint 1 TECH.

- The membership ratio is set at 50 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 56250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 4 days. They will require at least 80% support, and a minimum of 10% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 48 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 5000.0 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=400000&tgihr=80.0&maxihr=200.0&ihtr=1000000&ihmaxr=15000000&hor=50&hpd=28&her=12&ht=7&sr=80&maq=10&vdd=4&vbh=8&rqh=48&tfx=5000.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|1,000,000|
|Maximum Goal (wxDai)|15,000,000|
|Minimum Goal (wxDai)|400,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|80.0|
|Impact Hour Rate at Infinity (wxDai/IH)|200.0|
|Hatch Membership Ratio (wxDai/CSTK)|50|
|Hatch Period (days)|28|
|Hatch Minting rate (TECH/wxDai)|12|
|Hatch Tribute (%)|7|
|Support Required (%)|80|
|Minimum Quorum (%)|10|
|Vote Duration (days)|4|
|Vote Buffer (hours)|8|
|Ragequit (hours)|48|
|Tollgate Fee (wxDai)|5,000.0|</a>

**Comment by GriffGreen** [comment]
> Lowered the vote duration to 4 days. I just can’t go lower than that. I tried to type “3” but kept deleting it.

hahahahaha

**Comment by GriffGreen** [comment]
I'm really surprised that you are proposing such a high % to Builders after the IH distribution discussion, but as long as we get 4 mil or so, its not so outrageous. I sort of wish this proposal had the target goal set to the 5 mil range (with the corresponding IH Rate at that goal so the IH curve stayed the same) otherwise this is a nice proposal.

**Comment by GriffGreen** [comment]
Amazing piece of Token Engineering this one! 715 votes, 3rd place, and posted very late so prob if we extended the vote it could have gotten more!
