### ISSUE TITLE
TECH: the one & only 1️⃣ token

### ISSUE THREAD

**Issue by santteegt** [CommonsBuild/TEC-Hatch-Vote#77]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=70&maxihr=300&ihtr=5000000&ihmaxr=9000000&hor=10&hpd=45&her=1e-07&ht=5&sr=80&maq=4&vdd=3&vbh=8&rqh=24&tfx=3000.0" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/57zyrl.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/1c1f086f-cc14-4a88-9495-8cf21c688a25)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/23cd4454-f8a2-4582-aac0-9c32c77b49a9)
            
## Hatch Strategy

<p>Very optimistic about reaching the max goal. TECH max supply of 1 so contributors can only hold a fraction of the TECommons. Inspired by https://fraction.fyi/</p>
            
## DAO Strategy

<p>Encourage participation of community members that may hold small fractions of TECH</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 45 days.

- The target goal will be 5000000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 9000000 wxDai.

- Backers will need to send in 10000000.0 wxDai to mint 1 TECH.

- The membership ratio is set at 10 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 11250  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 3 days. They will require at least 80% support, and a minimum of 4% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 3000.0 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=70&maxihr=300&ihtr=5000000&ihmaxr=9000000&hor=10&hpd=45&her=1e-07&ht=5&sr=80&maq=4&vdd=3&vbh=8&rqh=24&tfx=3000.0" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|5,000,000|
|Maximum Goal (wxDai)|9,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|70|
|Impact Hour Rate at Infinity (wxDai/IH)|300|
|Hatch Membership Ratio (wxDai/CSTK)|10|
|Hatch Period (days)|45|
|Hatch Minting rate (TECH/wxDai)|1e-07|
|Hatch Tribute (%)|5|
|Support Required (%)|80|
|Minimum Quorum (%)|4|
|Vote Duration (days)|3|
|Vote Buffer (hours)|8|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|3,000.0|</a>

**Comment by GriffGreen** [comment]
hahahaha you are ridiculous

**Comment by GriffGreen** [comment]
voting for it

**Comment by GriffGreen** [comment]
Thank you for submitting this one @santteegt! We are closing all the submissions. This submission didn't get very many votes but it was great! and it inspired a lot of people, it helped make me make #78 and interpolate for 21 mil tokens :-D
