### ISSUE TITLE
Chuy's Final Frankenstein (Lil' bit of 8 #50, lil' bit of Zepti's #57, spiced with HHT maximalism #60)

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/TEC-Hatch-Vote#79]
## Check out my proposal for the Hatch! <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=80&maxihr=188.0&ihtr=1000000&ihmaxr=12000000&hor=24&hpd=30&her=0.75&ht=8&sr=80&maq=8&vdd=4&vbh=8&rqh=24&tfx=1000" target="_blank">Click here to preload the Hatch Configuration Dashboard with my parameters if you think you can do better</a>.

![image](https://i.imgflip.com/58sjtb.jpg)

# Graphical Summary

![image](https://hcti.io/v1/image/b9d13c7c-5c4f-4ba0-b433-fe82f0d61019)

## Graph Descriptions

- Top Left, **Impact Hour Rate vs wxDai Collected**: The Impact Hour Rate determines the Minting Rate for Builders, making 1 Impact Hour equivalent to sending this amount of wxDai to the Hatch.
- Top Right, **Proposal Acceptance Criteria**: Shows the range of possibilities for DAO vote outcomes and whether they succeed or not given the Support Required & Minimum Quorum I chose.
- Bottom Left, **Backer's Rage Quit % vs wxDai Collected**: The Backer's Rage Quit % is the percent of wxDai that the Backers sent to the Hatch that would be returned if they decide to Ragequit.
- Bottom Right, **Redeem-ability of the DAO's wxDai**: Shows who has rights to the wxDai held by the DAO. All of the DAO's funds are collectively governed but some can be withdrawn if token holders Ragequit. This shows the results of my parameter choices at the 3 different goals.

# Simulated Outcomes

![image](https://hcti.io/v1/image/82d5acc5-7326-42e1-8e91-d52db572d7bf)
            
## Hatch Strategy

<p>This is it: I think goals are reachable, builders are rewarded, backers can participate. Collective conviction is needed, so I set the Hatch Tribute at 8% which is on of the options I've seen the community accept the most.</p>
            
## DAO Strategy

<p>Not too hot, not too cold.</p>
            
# Summary

  <h2>Hatch Details</h2>

- Trusted Seed members can send wxDai to the Hatch for 30 days.

- The target goal will be 1000000 wxDai, with a minimum of 800000 wxDai necessary for the TEC Hatch DAO to be launched and a cap at 12000000 wxDai.

- Backers will need to send in 1.3333333333333333 wxDai to mint 1 TECH.

- The membership ratio is set at 24 wxDai/CSTK, so a Trusted Seed member with the minimum CSTK Score of 1125 CSTK can send up to 27000  wxDai to the Hatch.

<h2>TEC Hatch DAO Voting Details</h2>

- Proposals will be voted on for 4 days. They will require at least 80% support, and a minimum of 8% of the TECH Tokens will have to vote yes for a proposal to pass.

- TECH token holders will have 24 hours to exit the DAO if they don't like the result of a vote (as long as they didn't vote yes) before it is executed.

- There will be a minimum of 8 hours between proposals so people always have time to exit safely if they voted yes on a previous vote, this means we can have at most 1095 votes per year.

- To prevent griefing attacks, it will cost 1000 wxDai to make a proposal.

If you have Impact Hours, you can see how much money you will get with my configuration <a href="https://params.tecommons.org/hatch?ihminr=800000&tgihr=80&maxihr=188.0&ihtr=1000000&ihmaxr=12000000&hor=24&hpd=30&her=0.75&ht=8&sr=80&maq=8&vdd=4&vbh=8&rqh=24&tfx=1000" target="_blank">here, just check out the Impact Hour Results table.
            
# My Hatch Configuration

| Parameter|Value|
|:-|-:|
|Target Goal (wxDai)|1,000,000|
|Maximum Goal (wxDai)|12,000,000|
|Minimum Goal (wxDai)|800,000|
|Impact Hour Rate at Target Goal (wxDai/IH)|80|
|Impact Hour Rate at Infinity (wxDai/IH)|188.0|
|Hatch Membership Ratio (wxDai/CSTK)|24|
|Hatch Period (days)|30|
|Hatch Minting rate (TECH/wxDai)|0.75|
|Hatch Tribute (%)|8|
|Support Required (%)|80|
|Minimum Quorum (%)|8|
|Vote Duration (days)|4|
|Vote Buffer (hours)|8|
|Ragequit (hours)|24|
|Tollgate Fee (wxDai)|1,000|</a>

**Comment by GriffGreen** [comment]
This is a great piece of Token Engineering Chuy, closing all issues, but seriously this was a very nice proposal encapsulating the wisdom of the crowds
