### ISSUE TITLE
Got to start somewhere : Conservative raise, Cultural build around 33% for target raise 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/TEC-Hatch-Vote#9]
<h1>Parameters</h1>

| Parameters                          |   Values |
|:------------------------------------|---------:|
| Target raise (wxDai)                |   500000 |
| Maximum raise (wxDai)               |  5000000 |
| Minimum raise (wxDai)               |   300000 |
| Impact hour slope (wxDai/IH)        |      847 |
| Maximum impact hour rate (wxDai/IH) |      300 |
| Hatch oracle ratio (wxDai/CSTK)     |        5 |
| Hatch period (days)                 |       14 |
| Hatch exchange rate (TECH/wxDai)    |        1 |
| Hatch tribute (%)                   |       10 |
| Support required (%)                |       55 |
| Minimum accepted quorum (%)         |       10 |
| Vote duration (days)                |       10 |
| Vote buffer (hours)                 |        2 |
| Rage quit (hours)                   |       24 |
| Tollgate fee (wxDai)                |      100 |
            
<h1>Results</h1>

<p></p>

- It costs 100 wxDai to make a proposal.

- Votes will be voted on for 10 days.

- TECH token holders will have 24 Hours to exit the DAO if they don't like the result of a vote (as long as they don't vote yes).

- There will be a minimum of 2 hours between proposals so people can exit safely in weird edge case scenarios.

- A proposal that passes can be executed 26 hours after it was proposed.

- A CSTK Token holder that has 2000 CSTK can send a max of 10000 wxDai to the Hatch.

Play with my parameters [here](https://params.tecommons.org/hatch?ihminr=300000&hs=847&maxihr=300&ihtr=500000&ihmaxr=5000000&hor=5&hpd=14&her=1&ht=10&sr=55&maq=10&vdd=10&vbh=2&rqh=24&tfx=100).

To see the value of your individual Impact Hours, click [here to go to the Hatch Config Dashboard with these parameters](https://params.tecommons.org/hatch?ihminr=300000&hs=847&maxihr=300&ihtr=500000&ihmaxr=5000000&hor=5&hpd=14&her=1&ht=10&sr=55&maq=10&vdd=10&vbh=2&rqh=24&tfx=100) and explore the Impact Hour Results table.
            

<h1>Output Charts</h1>

![image](https://hcti.io/v1/image/2e6cc9a0-8f6c-4ccb-8f90-01de08c017b2)

<h1>Output Scenarios</h1>

![image](https://hcti.io/v1/image/3e7bd43f-de4b-4a13-9be1-d5afc4ebca64)

**Comment by GriffGreen** [comment]
Closing this issue because math is wrong in some of the outputs... Please re-propose!
